namespace PMS.Common.Enums
{
    public enum MessageType
    {
        GET_SUPPORTED_CARD_TYPES = 1,
        GET_USER_DETAILS = 2,
        GET_USER_ACCOUNT_DETAILS = 3,
        GET_TRANSACTION_LOG = 4,
        BI_VISA_PREPAID = 5,
        BI_1LINK_PREPAID = 6,
        CW_VISA_PREPAID = 7,
        CW_1LINK_PREPAID = 8,
        MERCHANT_TOPUP = 9,
        PREPAID_IBFT = 10,

        //Users
        GET_USERS = 11,
        CREATE_SEC_USER = 12,
        GET_USER_BY_ID = 13,
        GET_USER_GROUPS = 25,
        GET_USER_ENTITIES = 26,
        UPDATE_SEC_USER = 22,
        ADD_SEC_USER = 31,
        UPDATE_USER_STATUS = 46,
        UPDATE_USER_PASSWORD = 51,
        FORGET_PASSWORD = 52,
        GET_ALL_POLICIES = 92,
        SEARCH_USER = 159,
        DELETE_USER = 175,
        GET_USER_POLICY = 197,
        GET_USER_PHOTOGRAPH = 1022,
        GET_AD_USER_BY_ID = 9663,

        // MakerChecker
        ADD_CHECKER_DATA = 33,
        GET_CHECKER_MAIN_DATA = 34,
        GET_CHECKER_MAIN_DATA_BY_ID = 300,
        CHECKER_REQUEST = 36,
        GET_CHECKER_FILTER_DATA = 155,

        //Common
        GET_ALL_MARITAL_STATUSES = 47,
        GET_ALL_GENDERS = 48,
        GET_ALL_NATIONALITIES = 49,
        GET_ALL_OCCUPATIONS = 50,
        GET_ALL_NOTIFICATION_TYPE = 234,
        CHECK_CUSTOMER_ALREADY_EXIST = 235,
        GET_ALL_TITLES = 238,
        GET_ALL_CARD_TYPE = 241,

        GET_ALL_ENTITIES = 23,
        GET_ALL_GROUPS = 24,
        UPDATE_STATUS = 32,

        GET_SYSTEM_CONFIGURATION = 62,

        GET_ALL_FEES_TYPE = 116,
        GET_ALL_DELIVERY_CHANNELS = 169,
        GET_ALL_TRANSACTION_CODES = 170,

        GET_ALL_MARKET_SEGMENTS = 30007,
        GET_ALL_PROGRAMS_COM = 30014,

        GET_CHANNELS_OR_NETWORKS = 30008,


        GET_TRANSACTION_CODES_BY_CHANNEL_OR_NETWORK = 40002,

        GET_DEFAULT_CURRENCY = 185,
        GET_ALL_PREPAID_NETWORKS = 207,
        GET_ALL_SWITCH_ERROR_CODES = 208,
        GET_ALL_CITIES = 200,
        GET_ALL_NETWORKS = 1008,
        GET_ALL_CARD_CATEGORY = 1013,

        GET_ALL_BRANCHES_BY_USER = 40065,

        //Currency
        GET_ALL_CURRENCY = 35,
        CREATE_CURRENCY = 37,
        GET_CURRENCY = 38,
        UPDATE_CURRENCY = 39,
        SEARCH_CURRENCY = 40,


        //Branch
        SEARCH_BRANCH = 41,
        GET_ALL_BRANCHES = 43,
        GET_ALL_USER_BRANCHES = 168,
        CREATE_BRANCH = 42,
        GET_BRANCH = 44,
        UPDATE_BRANCH = 45,
        GET_ALL_BRANCH_SHORT_INFO = 198,

        GET_CARD_FOR_PIN_PRINTING = 1111,

        //Product
        CREATE_CARD_PRODUCT = 14,
        GET_ALL_PRODUCTS = 15,
        GET_PRODUCT = 16,
        UPDATE_CARD_PRODUCT = 17,
        SEARCH_PRODUCT = 161,


        //Country
        CREATE_COUNTRY = 93080,
        SEARCH_COUNTRY = 93081,
        UPDATE_COUNTRY = 93082,

        //Product BIN Range
        CREATE_PRODUCTBINRANGE = 93090,
        SEARCH_PRODUCTBINRANGE = 93091,
        UPDATE_PRODUCTBINRANGE = 93092,
        GET_PRODUCTBINRANGEBYID = 93093,

        //Program
        CREATE_PROGRAM = 57,
        UPDATE_PROGRAM = 58,
        GET_ALL_PROGRAMS = 59,
        GET_PROGRAM_BY_CODE = 60,
        SEARCH_PROGRAM = 61,
        GET_NEW_PROGRAM_DATA = 154,

        //CustomerType
        ADD_CUSTOMER_TYPE = 27,
        GET_ALL_CUSTOMER_TYPES = 28,
        GET_CUSTOMER_TYPE = 29,
        UPDATE_CUSTOMER_TYPE = 30,
        SEARCH_CUSTOMER_TYPE = 162,

        //Nationality
        ADD_NATIONALITY = 989,
        GET_NATIONALITY = 991,
        UPDATE_NATIONALITY = 992,
        SEARCH_NATIONALITY = 993,
        IS_VALID_NATIONALITY_MAPPING_ID = 994,

        // Bank
        ADD_BANK = 1010,
        GET_BANK = 1009,
        GET_ALL_BANKS = 1003,
        UPDATE_BANK = 1011,
        SEARCH_BANK = 1012,

        // FamilyPackages
        GET_ALL_Family_Packages = 60070,





        //City
        CREATE_CITY = 1014,
        SEARCH_CITY = 1015,
        UPDATE_CITY = 1016,
        VALIDATE_CITY_MAPPINGID = 1017,

        //Account status
        CREATE_ACCOUNT_STATUS = 1018,
        UPDATE_ACCOUNT_STATUS = 1019,
        SEARCH_ACCOUNT_STATUS = 1020,
        VALIDATE_ACCOUNT_STATUS_MAPPINGID = 1021,

        //Group
        GET_GROUP_BY_ID = 64,
        UPDATE_GROUP = 65,
        ADD_GROUP = 66,
        GET_ALL_PERMISSIONS = 67,
        SEARCH_GROUP = 158,
        DELETE_GROUP = 985,
        GET_GROUP_USERS = 40066,

        //Customer
        CREATE_CUSTOMER = 53,
        UPDATE_CUSTOMER = 54,
        GET_ALL_CUSTOMERS = 55,
        GET_CUSTOMER_BY_RELATIONSHIP_NUM = 56,
        SEARCH_CUSTOMER = 78,
        GET_CUSTOMER_ACCOUNT_DETAILS = 69,
        GET_CUSTOMER_CARD_DETAILS = 68,
        UPDATE_CUSTOMER_STATUS = 70,
        GET_CUSTOMER_STATUS_REASON = 76,
        GET_ALL_CUSTOMER_STATUS = 77,
        GET_CUSTOMER_PROFILE_SETUP_DATA = 71080,
        GET_CUSTOMER_LIMIT = 71081,
        GET_CUSTOMER_PERMISSION = 71082,
        GET_CUSTOMER_LIMIT_EXCEPTION = 71083,
        GET_CUSTOMER_ACCOUNT = 71084,

        //Account
        GET_ALL_ACCOUNTS = 71,
        SEARCH_ACCOUNT = 72,
        GET_ACCOUNT_BY_ACCOUNT_NUMBER = 73,
        INSERT_ACCOUNT = 74,
        UPDATE_ACCOUNT = 75,

        GET_ALL_COUNTRIES = 79,
        GET_ALL_ACCOUNT_TYPES = 80,
        VAILDATE_GL_ACCOUNT = 987,
        UPDATE_LIMIT_EXCEPTION = 93094,
        UPDATE_CUSTOMER_LIMIT_EXCEPTION = 93095,
        UPDATE_CARD_LIMIT_EXCEPTION = 93096,
        GET_CARDS_DROPDOWNS = 93100,
        GET_CARDS_LIMIT = 93101,
        GET_CARDS_PERMISSSIONS = 93102,
        GET_CARDS_ACCOUNT = 93103,
        GET_CARDS_CUSTOMER = 93104,
        GET_CARDS_LIMIT_EXCEP = 93105,

        GET_ACCOUNT_PROFILE_SETUP_DATA = 100001,
        GET_ACCOUNT_ACTIVITIES_SETUP_DATA = 100002,
        GET_ACCOUNT_LINK_SETUP_DATA = 100003,
        GET_ACCOUNT_LIMIT_SETUP_DATA = 100004,

        GET_ACCOUNT_BY_ACCOUNT_NUMBER_PROFILE = 100005,
        GET_ACCOUNT_BY_ACCOUNT_NUMBER_ACTIVITIES = 100006,
        GET_ACCOUNT_BY_ACCOUNT_NUMBER_LIMIT = 100007,
        GET_ACCOUNT_BY_ACCOUNT_NUMBER_LINK = 100008,
        DELETE_BANK = 100009,

        //Card
        GET_ALL_CARDS = 149,
        CREATE_CARD = 150,
        GET_CARD_BY_PAN = 151,
        UPDATE_CARD = 152,
        SEARCH_CARD = 153,
        GET_ALL_PROGRAM_OP = 163,
        GET_ALL_PRODUCT_OP = 167,
        GET_ALL_BRANCH_OP = 164,
        GET_ALL_CARD_STATUS_OP = 165,
        GET_ALL_APP_STATUS_OP = 166,

        GET_ALL_PERSON_NON_PERSON_OP = 171,
        GET_ALL_LINKED_NOT_LINKED_OP = 172,
        GET_ALL_BATCH_STATUS_OP = 173,

        GET_CUST_BY_REL = 182,
        LINK_CARD_CUSTOMER = 183,

        CARD_REQUEST_BATCH_UPDATE_PROGRESS_FLAG = 184,
        RECHARGE_CARD_TOPUP = 212,
        GET_CARD_ACCOUNT_DETAILS_BY_PAN = 211,
        GET_CARD_ACCOUNT_DETAILS_BY_CARD_ID = 239,
        CLOSE_CARD = 213,

        //Prepaid Batch
        GET_ALL_PREPAID_BATCHES = 174,
        GET_ALL_PREPAID_BATCH_STATUS_OP = 175,
        GET_PREPAID_BATCH_BY_ID = 176,
        UPDATE_PREPAID_BATCH = 177,
        SEARCH_PREPAID_BATCH = 178,


        //Account Type

        UPDATE_ACCOUNT_TYPE = 81,
        ADD_ACCOUNT_TYPE = 82,
        GET_ACCOUNT_TYPE_CODE = 83,
        Get_ALL_ACCOUNT_TYPE = 90,
        SEARCH_ACCOUNT_TYPE = 160,

        //Permission Profile
        GET_ALL_PERMISSION_PROFILE_LIST = 84,
        SAVE_PERMISSION_PROFILE_VARIATION = 85,
        GET_PERMISSION_PROFILE_VARIATION = 86,
        GET_PERMISSION_PROFILE_FIELD = 87,

        UPDATE_PERMISSION_PROFILE = 88,
        SEARCH_PERMISSION_PROFILE_VARIATION = 89,

        UPDATE_PERMISSION_PROFILE_VARIATION = 88,

        GET_PERMISSION_PROFILE_FIELD_VALUE = 91,

        GET_ALL_PERMISSION_PROFILE_FIELDS = 93,

        GET_PERMISSION_PROFILE_FIELDS_VAL_BY_PROF_VAR_ID = 100,
        VALIDATE_PERMISSION_PROFILE_FIELD = 178,
        DELETE_PERMISSION_PROFILE_VAR = 984,





        //Card GNERATION = CG
        GET_ALL_CARD_REQUESTS = 94,
        GET_ALL_PROGRAM_CG = 95,
        CREATE_BATCH_CARD_REQUEST = 96,
        SEND_BATCH_CARD_REQUEST_FOR_APPROVAL = 174,
        GET_ALL_BRANCH_CG = 97,
        GET_CARD_REQUEST_BY_FILTER = 98,
        GET_CARD_FOR_PIN = 188,
        GET_CARD_REQUEST_BY_CHECKER = 177,
        GET_CARD_REQUEST_BY_BATCH_ID = 99,
        CARD_REQUEST_CHECKER = 101,
        CARD_GENERATION_MAKER = 102,
        GET_ALL_BATCH_STATUS = 176,

        GET_CARD_REQ_NON_PERSON_BY_FILTER = 108,
        GET_CARD_NON_PERSON_DETAILS = 113,
        PROCESS_CARD_GENERATION_MAKER = 114,


        CARD_GENERATION_CHECKER = 112,

        GET_GENERATED_CARD = 134,

        CARD_EXPORT_REQUEST = 133,


        PIN_PRINTING_REQUEST = 136,
        PIN_GENERATION = 194,
        FORCE_PIN_GENERATION = 195,
        CHECK_BIN_RANGE = 988,

        //Charge Profile


        SAVE_CHARGE_PROFILE_VARIATION = 109,
        GET_ALL_CHARGE_PROFILE = 110,
        GET_CHARGE_PROFILE_VARIATION_DATA = 111,
        GET_CHARGE_PROFILE_VARIATIONS_BY_PROFILE = 115,
        GET_CHARGE_PROFILE_FIELDS = 119,
        UPDATE_CHARGE_PROFILE_VARIATION_DATA = 118,
        GET_CHARGE_PROFILE_FIELD_VALUE_BY_PROF_VAR_ID = 120,
        SEARCH_CHARGE_PROFILE_VARIATION = 121,
        VALIDATE_CHARGE_PROFILE_FIELD = 179,

        //Limit Profile Customer

        GET_ALL_LIMIT_PROFILE_CUSTOMER = 40001,
        SAVE_LIMIT_PROFILE_CUSTOMER = 40003,
        GET_LIMIT_PROFILE_CUSTOMER = 40004,
        UPDATE_LIMIT_PROFILE_CUSTOMER = 40005,
        SEARCH_LIMIT_PROFILE_CUSTOMER = 40006,
        SAVE_LIMIT_PROFILE_CARD = 40007,
        UPDATE_LIMIT_PROFILE_CARD = 40008,
        SAVE_LIMIT_PROFILE_ACCOUNT = 40009,
        UPDATE_LIMIT_PROFILE_ACCOUNT = 40010,
        SEARCH_LIMIT_PROFILE_ACCOUNT = 40011,
        GET_LIMIT_PROFILE_ACCOUNT = 40012,
        GET_ALL_LIMIT_PROFILE_ACCOUNT = 40013,
        SEARCH_LIMIT_PROFILE_CARD = 40014,
        GET_LIMIT_PROFILE_CARD = 40015,
        GET_ALL_LIMIT_PROFILE_CARD = 40016,
        GET_TRANSACTIONS_BY_CRITERIA = 40017,
        GET_LIMIT_PROFILES = 40018,
        LINK_LIMIT_PROFILE_CUSTOMER = 40019,
        DE_LINK_CUSTOMER_ACCOUNT = 40020,
        GET_ALL_NOT_LINKED_ACCOUNT = 40021,
        LINK_CUSTOMER_ACCOUNT = 40022,
        UPDATE_CUSTOMER_PERMISSION = 40023,

        GET_ALL_ACCOUNT_OFFICERS = 40024,
        LINK_LIMIT_PROFILE_ACCOUNT = 40025,
        UPDATE_ACCOUNT_PERMISSION = 40026,
        GET_ALL_AVAILABLE_CUSTOMERS = 40027,
        LINK_ACCOUNT_CUSTOMER = 40028,
        DE_LINK_ACCOUNT_CUSTOMER = 40029,

        GET_ALL_AVAILABLE_CARDS = 40030,
        LINK_ACCOUNT_CARD = 40031,
        DE_LINK_ACCOUNT_CARD = 40032,

        LINK_LIMIT_PROFILE_CARD = 40033,
        UPDATE_CARD_PERMISSION = 40034,
        GET_ALL_AVAILABLE_ACCOUNTS = 40035,
        DE_LINK_CARD_ACCOUNT = 40036,
        LINK_CARD_ACCOUNT = 40037,

        GET_ALL_ACTIVATION_STATUSES = 40038,


        GET_LIMIT_PROFILE_VARIATION_DATA = 127,
        GET_ALL_LIMIT_PROFILE_FIELDS = 128,
        SEARCH_LIMIT_PROFILE_CUSTOMER_VARIATION = 40000,
        GET_LIMIT_PROFILE_VARIATIONS_BY_PROFILE = 130,
        GET_ALL_IDENTIFICATION_FIELDS_BY_PROFILE = 131,
        SAVE_LIMIT_PROFILE_VARIATION_DATA = 156,
        UPDATE_LIMIT_PROFILE_VARIATION_DATA = 145,
        GET_LIMIT_PROFILE_FIELD_VALUE_BY_PROF_VAR_ID = 146,
        VALIDATE_LIMIT_PROFILE_FIELD = 186,

        //Limit Profile Group

        GET_ALL_LIMIT_PROFILES_GROUP = 135,
        SAVE_LIMIT_PROFILE_GROUP_DETAILS = 137,
        UPDATE_LIMIT_PROFILE_GROUP_DETAILS = 138,
        SEARCH_LIMIT_PROFILE_GROUP = 139,
        GET_LIMIT_PROFILE_GROUP_DATA = 140,
        GET_LIMIT_PROFILE_GROUP_DETAILS_BY_LIMIT_ID = 141,
        GET_ALL_INTERNALFIELDS_RDV_FOR_IDENTIFICATIONFIELDS = 157,
        GET_ALL_PROFILE_CYCLE_LENGTH = 187,

        // ProgramTypes
        GET_ALL_PROGRAM_TYPES = 103,
        UPDATE_PROGRAM_TYPE = 104,
        ADD_PROGRAM_TYPE = 105,
        GET_PROGRAM_TYPE_CODE = 106,
        Get_ALL_PROGRAM_TYPE = 107,

        GET_LIMIT_PROFILE_GROUP_DETAIL_BY_LIMIT_DETAIL_ID = 142,
        UPDATE_LIMIT_PROFILE_DETAIL_VALUES = 143,
        DELETE_LIMIT_PROFILE_DETAIL = 144,
        GET_ALL_ACCOUNT_STATUS = 148,
        GET_ALL_CARDS_CUST_LINK = 199,
        LINK_CARDS_CUSTOMER = 201,
        CUST_SEARCH_CARD = 206,
        // Password Policy 
        GET_ALL_PASSWORD_POLICIES = 189,
        GET_PASSWORD_POLICY_BY_ID = 190,
        SAVE_PASSWORD_POLICY = 191,
        UPDATE_PASSWORD_POLICY = 192,
        SEARCH_PASSWORD_POLICY = 193,
        GET_ALL_PASSWORD_EXPRESSIONS = 196,

        // Transaction Log
        GET_ALL_TRAN_LOGS = 202,
        GET_TRAN_LOG_BY_ID = 203,
        SEARCH_TRAN_LOG = 204,
        EXEC_FULL_REVERSAL_FOR_TRAN = 205,
        GET_TRANSACTION_SUMMARY_DETAILS = 40018,

        //CARD OPTION
        BATCH_CARD_REPLACEMENT = 210,
        GET_CARD_ACCOUNT_BY_PAN = 214,
        CARD_MANUAL_ADJUSTMENT = 215,

        //Transaction DashBorad
        GET_TRANSACTION_DASHBOARD_DATA = 40067,
        GET_TOP_FIVE_TRANS_DAILY = 209,
        GET_TOP_FIVE_TRANS_WEEKLY = 216,
        GET_TRANS_SUCCESS_DECLINE_DAILY = 217,
        GET_TRANS_SUCCESS_DECLINE_WEEKLY = 218,
        GET_CHANNEL_WISE_TRANS_DAILY = 219,
        GET_CHANNEL_WISE_TRANS_WEEKLY = 220,
        GET_TRANSACTION_PEAK_MONTH_DAY = 221,
        GET_TOP_FIVE_MERCHANT_DAILY = 222,
        GET_TOP_FIVE_MERCHANT_WEEKLY = 223,
        GET_PROGRAM_WISE_TRANS_DAILY = 224,
        GET_PROGRAM_WISE_TRANS_WEEKLY = 225,
        GET_PROGRAM_WISE_CARDS_DAILY = 226,
        GET_PROGRAM_WISE_CARDS_WEEKLY = 227,
        GET_CARDS_REISSUED_DAILY = 228,
        GET_CARDS_REISSUED_WEEKLY = 229,
        GET_CARDS_MARKED_HOT_DAILY = 230,
        GET_CARDS_MARKED_HOT_WEEKLY = 231,
        GET_TRANSACTION_FEES_DAILY = 232,
        GET_TRANSACTION_FEES_WEEKLY = 233,

        GET_TRAN_DASHBOARD_TRAN_SUMMARY_DAILY = 21022,
        GET_TRAN_DASHBOARD_TRAN_SUMMARY_WEEKLY = 21023,

        GET_TABLE_DISPLAY_NAMES = 986,
        //Approval
        GET_ALL_FROM_TABLES = 240,

        // Device Factory
        CREATE_DEVICE_FACTORY = 1023,
        UPDATE_DEVICE_FACTORY = 1024,
        SEARCH_DEVICE_FACTORY = 1025,
        GET_DEVICE_TYPE = 1026,
        GET_DEVICE_USAGE = 1027,

        //Langauge

        CREATE_LANGUAGE = 1031,
        UPDATE_LANGUAGE = 1032,
        SEARCH_LANGUAGE = 1033,

        // Search Filter
        GET_SEARCH_FILTERS = 1028,
        GET_DATA_FOR_COMBOBOX = 1029,
        GET_DATA_FOR_CHECK_BOX_LIST = 1030,

        #region RDV CONFIGURATION

        GET_ALL_SWITCH_CONFIGURATION = 9664,
        GET_SWITCH_CONFIGURATION_BY_CODE = 9665,
        UPDATE_SWITCH_CONFIGURATION = 9666,
        SAVE_SWITCH_CONFIGURATION = 9667,
        FILTER_SWITCH_CONFIGURATION = 9668,

        //LINK_ACCOUNT_WITH_CPR = 9669,

        GET_ALL_CLUSTER_CONFIGURATION = 20061,
        GET_CLUSTER_CONFIGURATION_BY_CODE = 20062,
        UPDATE_CLUSTER_CONFIGURATION = 20063,
        SAVE_CLUSTER_CONFIGURATION = 20064,
        FILTER_CLUSTER_CONFIGURATION = 20065,

        GET_ALL_CLUSTERNODE_CONFIGURATION = 20066,
        GET_CLUSTERNODE_CONFIGURATION_BY_CODE = 20067,
        UPDATE_CLUSTERNODE_CONFIGURATION = 20068,
        SAVE_CLUSTERNODE_CONFIGURATION = 20069,
        FILTER_CLUSTERNODE_CONFIGURATION = 20070,

        GET_ALL_CLUISTERS = 20060,


        GET_ALL_ADAPTER_CONFIGURATION = 20075,
        GET_ADAPTER_CONFIGURATION_BY_CODE = 20074,
        UPDATE_ADAPTER_CONFIGURATION = 20073,
        SAVE_ADAPTER_CONFIGURATION = 20072,
        FILTER_ADAPTER_CONFIGURATION = 20071,

        GET_ALL_NODES = 20059,
        GET_ALL_ADAPTER_TYPES = 20058,
        GET_ALL_MODULES = 20057,
        //GET_ALL_NETWORKS = 20056,


        // Customer Permission Profile
        DELETE_PERMISSION_PROFILE_CUSTOMER = 30001,
        GET_ALL_PERMISSION_PROFILE_CUSTOMER = 30002,
        SAVE_PERMISSION_PROFILE_CUSTOMER = 30003,
        GET_PERMISSION_PROFILE_CUSTOMER = 30004,
        UPDATE_PERMISSION_PROFILE_CUSTOMER = 30005,
        SEARCH_PERMISSION_PROFILE_CUSTOMER = 30006,

        // Account Permission Profile
        GET_ALL_PERMISSION_PROFILE_ACCOUNT = 30009,
        SAVE_PERMISSION_PROFILE_ACCOUNT = 30010,
        GET_PERMISSION_PROFILE_ACCOUNT = 30011,
        UPDATE_PERMISSION_PROFILE_ACCOUNT = 30012,
        SEARCH_PERMISSION_PROFILE_ACCOUNT = 30013,

        // Card Permission Profile
        GET_ALL_PERMISSION_PROFILE_CARD = 30015,
        SAVE_PERMISSION_PROFILE_CARD = 30016,
        GET_PERMISSION_PROFILE_CARD = 30017,
        UPDATE_PERMISSION_PROFILE_CARD = 30018,
        SEARCH_PERMISSION_PROFILE_CARD = 30019,

        // New Card Request        
        GET_ALL_CARD_TYPES_BY_PRODUCT_CODE = 30020,
        SEARCH_NEW_CARD_REQUEST = 30021,
        GET_RECORD_BY_CODE_NEW_CARD_REQUEST = 30022,
        SAVE_NEW_CARD_REQUEST = 30023,

        // Card generation
        GET_CARD_REQUESTS = 30024,
        GET_RECORD_BY_CODE_CARD_GENERATION = 30025,
        UPDATE_CARD_REQUEST = 30026,
        PROCESS_NEW_CARD_GENERATION = 30027,

        // Card Operations
        GET_OPRATION_TYPES = 30028,
        SEARCH_CARD_REPLACEMENT_SUPLEMENTARY = 30029,
        PROCESS_REPLACEMENT_CARD = 30030,
        PROCESS_SUPLEMENTARY_CARD = 30031,
        GET_ALL_CARD_STATUS = 30032,
        SEARCH_EXPIRED_CARDS = 30033,
        SEARCH_CARD_FOR_CHANGE_STATUS = 30034,
        SEARCH_CARD_FOR_CHANGE_TYPE = 30035,
        PROCESS_EXPIRED_CARD = 30036,
        PROCESS_CHANGE_CARD_STATUS = 30037,
        PROCESS_CHANGE_CARD_TYPE = 30038,

        //PIN GENERATION
        GET_CARDS_FOR_PIN_GENERATION = 30039,
        PROCESS_PIN_GENERATION = 30040,
        PROCESS_FORCED_PIN_GENERATION = 30041,

        //PIN PRINT
        GET_CARDS_FOR_PIN_PRINT = 30042,
        PROCESS_PIN_PRINT = 30043,
        PROCESS_FORCED_PIN_PRINT = 30044,
        GET_EXPORT_CARDS = 30045,
        PROCESS_EXPORT_CARDS = 30046,


        //CARD PRINT
        GET_CARDS_FOR_CARD_PRINT = 40059,
        PROCESS_CARD_PRINT = 40060,
        PROCESS_FORCED_CARD_PRINT = 40061,


        PROCESS_IMPORT = 30048,
        REFRESH_REPORTS = 30047,
        #endregion
        // Switch Configuration
        GET_SWITCH_DASHBOARD_COMP = 20081,
        TOGGLE_SERVICE_HEALTH = 20082,

        //LiveMonitoring
        GET_TRANSACTION_MONITORING_LOGS = 20086,

        //SAFLog
        CLEAR_SAF = 20083,
        UPDATE_RETRY_COUNT = 20084,
        SEARCH_SAF_LOG = 20085,
        //PIN Mailer
        GET_ALL_FORMAT_FIELDS = 20087,

        GET_PINMAILER_CONFIG_DATA_BY_CARDTYPECODE = 20088,
        GET_PROD_FORMAT_BY_PROGRAMCODE = 20089,

        GET_USER_DASHBOARD_DATA = 40058,


        #region ATM Operations
        // ATM Region
        ADD_REGION = 40039,
        GET_REGION = 40040,
        UPDATE_REGION = 40041,
        SEARCH_REGION = 40042,

        // ATM Favorite Group
        ADD_FAVORITE_GROUP = 40043,
        GET_FAVORITE_GROUP = 40044,
        UPDATE_FAVORITE_GROUP = 40045,
        SEARCH_FAVORITE_GROUP = 40046,
        GET_SETUP_DATA_FAVORITE_GROUP = 40056,
        SEARCH_ATM_TERMINAL_FAVORITE_GROUP = 40057,

        //ATM Configuration
        SEARCH_ATM_TERMINALS = 20092,
        GET_ALL_ATM_TERMINALS = 20091,
        ADD_ATM_TERMINAL = 20093,
        UPDATE_ATM_TERMINAL = 20094,
        GET_ATM_TERMINAL_BY_ID = 20095,
        GET_TERMINAL_SETUP_DATA = 21007,
        GET_ALL_TIME_ZONES = 21001,
        GET_ALL_ATM_GROUPS = 21002,
        GET_ALL_REGIONS = 21003,
        GET_ALL_CASSETTES_PROFILE = 20096,
        GET_KEYDOWN_MECHANISM = 21005,
        GET_COMMUNICATION_MECHANISM = 21006,
        GENERATE_KEY = 21021,

        //Cassette Profile
        GET_CASSETTE_PROFILE_BY_ID = 20099,
        ADD_CASSETTE_PROFILE = 20098,
        UPADTE_CASSETTE_PROFILE = 21000,
        SEARCH_CASSETTE_PROFILE = 20097,
        // ATM Terminal Monitoring
        ATM_TERMINAL_MONITORING_GET_SETUP_DATA = 40047,
        ATM_TERMINAL_MONITORING_SEARCH = 40048,

        // ATM Command Processor
        ATM_COMMAND_PROCESSOR_GET_SETUP_DATA = 40049,
        ATM_COMMAND_PROCESSOR_SEARCH = 40050,
        ATM_COMMAND_PROCESSOR_HISTORY = 40051,
        ATM_COMMAND_PROCESSOR_SEND_ATM_COMMAND = 40052,

        // ATM SAF Log
        ATM_SAF_LOG_GET_SETUP_DATA = 40053,
        ATM_SAF_LOG_SEARCH = 40054,
        ATM_SAF_LOG_RESET = 40055, GET_CASSETTE_TYPE_ATM_DEVICE = 21020,
        //ATM Model / Type
        ADD_ATM_MODEL = 21009,
        SEARCH_ATM_MODEL = 21008,
        UPDATE_ATM_MODEL = 21010,
        GET_ALL_ATM_PROTOCOL = 21011,

        //Terminal Inquiry
        GET_TERMINAL_INQUIRY_SETUP_DATA = 21012,
        GET_ALL_TERMINAL_FOR_INQUIRY = 21013,
        SEARCH_TERMINAL_FOR_INQUIRY = 21014,
        TERMINAL_INQUIRY_BY_ID = 21015,

        //Suspect Transaction
        GET_SUSPECT_TRANSACTION_SETUP_DATA = 21016,
        SEARCH_SUSPECT_TRANSACTION = 21017,

        //ATM Locator
        GET_ATM_LOCATOR_SETUP_DATA = 21018,
        SEARCH_ATM_LOCATION = 21019,
        #endregion


        //Alert Configuration

        GET_ALL_ALERT_CONFIGURATION = 30049,
        SEARCH_ALERT_CONFIGURATION = 30050,
        GET_RECORD_BY_CODE_ALERT_CONFIGURATION = 30051,
        UPDATE_ALERT_CONFIGURATION = 30052,

        //Alert Groups
        GET_ALL_ALERT_GROUPS = 30053,
        SEARCH_ALERT_GROUPS = 30054,
        GET_RECORD_BY_CODE_ALERT_GROUPS = 30055,
        CREATE_ALERT_GROUPS = 30056,
        UPDATE_ALERT_GROUPS = 30057,
        GET_USER_BY_LOGIN_ID = 30063,

        //Alert Monitoring
        SEARCH_ALERT_MONITORING = 30058,
        GET_RECORD_BY_CODE_ALERT_MONITORING = 30059,
        UPDATE_ALERT_MONITORING = 30060,

        //Stand in processing
        SEARCH_STAND_IN_PROCESSING = 30061,
        CHANGE_STAND_IN_PROCESSING_MODE = 30062,

        // Switch Command Processor
        GET_ALL_NETWORKS_BY_UI_COM = 30064,
        SEARCH_NETWORKS_BY_UI_COM = 30065,
        GET_COMMAND_PROCESSOR_HISTORY = 30066,
        SEND_COMMAND_TO_SWITCH = 30067,
        GET_ALL_STATEMENT_FREQUENCY = 40062,
        GET_ALL_CITY_BY_COUNTRY = 40063,
        GET_ALL_RELATIONSHIP_TYPE = 40064,
        GET_ALL_IMD = 40068,

        //ATM Dashboard
        GET_ATM_DASHBOARD_DATA = 30068,

        //Manages Keys And Password
        GET_ALL_CRYPTO_HISTORY = 40069,
        SEARCH_CRYPTO_HISTORY = 40070,
        GET_ALL_CRYPTO_PERIOD = 40071,
        GET_PENDING_CRYPTO_PASSWORD_KEYS_REQUEST = 40072,
        PROCESS_CRYPTO_PASSWORD_KEYS_REQUEST = 40073,
        CANCEL_REQUEST_CRYPTO_PASSWORD_KEYS = 40074,
        CREATE_CRYPTO_PASSWORD_KEYS = 40075,

        GET_WALLBOARD_DATA = 40076,

        #region POSManagement
        SEARCH_MERCHANT_TYPE = 40077,


        SEARCH_PENDING_TERMINAL_REQUESTS = 30069,
        GET_RECORD_BY_CODE_TERMINAL_REQUEST = 30070,
        REJECT_TERMINAL_REQUEST = 30071,
        APPROVE_TERMINAL_REQUEST = 30072,

        CREATE_MERCHANT_TYPE = 40078,
        UPDATE_MERCHANT_TYPE = 40079,
        GET_MERCHANT_TYPE_BY_CODE = 40080,

        SEARCH_POS_LIMIT = 40081,
        CREATE_POS_LIMIT = 40082,
        UPDATE_POS_LIMIT = 40083,
        GET_POS_LIMIT = 40084,

        SEARCH_TRANSACTION_HISTORY = 40085,
        GET_TRANSACTION_DETAIL = 40086,
        GET_POS_TRANSACTION_CODE_LIST = 40087,
        DO_REFUDN = 40088,

        GET_CUSTOMER_BY_RELATIONSHIP_NUMBER = 40089,
        CREATE_BENEFICIARY = 40090,
        UPDATE_BENEFICIARY = 40091,
        GET_BENEFICIARY_BY_CODE = 40092,
        GET_BENEFICIARY_LIST = 40093,
        GET_SETUP_DATA = 40094,
        DELETE_BENEFICIARY = 40095,

        SEARCH_TERMINAL_TYPE = 30073,
        GET_RECORD_BY_CODE_TERMINAL_TYPE = 30074,
        CREATE_TERMINAL_TYPE = 30075,
        UPDATE_TERMINAL_TYPE = 30076,

        SEARCH_POS_TERMINAL = 30077,
        GET_RECORD_BY_CODE_POS_TERMINAL = 30078,
        CREATE_POS_TERMINAL = 30079,
        UPDATE_POS_TERMINAL = 30080,

        GET_ALL_MERCHANTS_BY_CORPORATE_CODE = 30081,
        GET_ALL_STORES_BY_MERCHANT_CODE = 30082,

        SEARCH_POS_PERMISSION = 30083,
        GET_RECORD_BY_CODE_POS_PERMISSION = 30084,
        CREATE_POS_PERMISSION = 30085,
        UPDATE_POS_PERMISSION = 30086,

        CREATE_CORPORATE = 50002,
        UPDATE_CORPORATE = 50003,
        SEARCH_CORPORATE = 50001,
        GET_BY_CODE_CORPORATE = 50004,
        GET_POS_PERMISSION_TRANSACTIONS = 50005,

        SEARCH_POS_MERCHANT = 30087,
        GET_RECORD_BY_CODE_POS_MERCHANT = 30088,
        CREATE_POS_MERCHANT = 30089,
        UPDATE_POS_MERCHANT = 30090,

        SEARCH_POS_STORE = 30091,
        GET_RECORD_BY_CODE_POS_STORE = 30092,
        CREATE_POS_STORE = 30093,
        UPDATE_POS_STORE = 30094,

        SEARCH_POS_FEE = 30096,
        GET_RECORD_BY_CODE_POS_FEE = 30097,
        CREATE_POS_FEE = 30098,
        UPDATE_POS_FEE = 30099,

        SEARCH_POS_COMMISSION = 30100,
        GET_RECORD_BY_CODE_POS_COMMISSION = 30101,
        CREATE_POS_COMMISSION = 30102,
        UPDATE_POS_COMMISSION = 30103,

        GET_POS_PERMISSION_TRANSACTIONS_EXCEPTIONS = 30104,

        GET_ALL_CORPORATE = 60001,
        GET_MERCHANT_BY_CORPORATE = 60002,
        GET_STORE_BY_MERCHANT = 60003,
        POS_MANUAL_ADJUSTMENT = 60004,
        UPDATE_POS_STORE_STATUS = 60005,
        UPDATE_POS_TERMINAL_STATUS = 60006,

        #endregion

        #region Master Card Settlement
        SEARCH_FIRST_PRESENTMENT = 40096,
        GET_FIRST_PRESENTMENT_SETUP_DATA = 40097,
        GET_FIRST_PRESENTMENT_BY_CODE = 40098,
        GET_FIRST_PRESENTMENT_FORM_SETUP_DATA = 40099,
        FIRST_PRESENTMENT_SEARCH_TRANSACTIONS_FOR_LINK = 40100,
        FIRST_PRESENTMENT_DO_LINK_WITH_AUTHORIZATION = 40101,
        FIRST_PRESENTMENT_DO_LINK_WITHOUT_AUTHORIZATION = 40102,
        FIRST_PRESENTMENT_DO_UN_LINK = 40103,
        DELETE_FIRST_PRESENTMENT = 40113,

        SEARCH_SECOND_PRESENTMENT = 40104,
        GET_SECOND_PRESENTMENT_SETUP_DATA = 40105,
        GET_SECOND_PRESENTMENT_BY_CODE = 40106,
        GET_SECOND_PRESENTMENT_FORM_SETUP_DATA = 40107,
        DELETE_SECOND_PRESENTMENT = 40114,

        GET_IMPORT_FORM_SETUP_DATA = 40108,
        GET_IMPORT_SEARCH_ZIP_FILES = 40109,
        GET_IMPORT_SEARCH_IPM_FILES = 40110,
        GET_IMPORT_SEARCH_IMP_MESSAGES = 40111,
        MOVE_ZIP_FILE = 40112,
        #endregion
        GET_ALL_2FA_OPTIONS = 30095,

        #region Merchnat
        CREATE_TERMINAL_REQUEST = 30105,
        SEARCH_ALL_TERMINAL_REQUESTS = 30106,

        #endregion

        #region Utility Bill

        SEARCH_UTILITY_CATEGORY = 60007,
        GET_RECORD_BY_CODE_UTILITY_CATEGORY = 60008,
        CREATE_UTILITY_CATEGORY = 60009,
        UPDATE_UTILITY_CATEGORY = 60010,
        DELETE_UTILITY_CATEGORY = 60011,

        SEARCH_UTILITY_SERVICE_TYPE = 60012,
        GET_RECORD_BY_CODE_UTILITY_SERVICE_TYPE = 60013,
        CREATE_UTILITY_SERVICE_TYPE = 60014,
        UPDATE_UTILITY_SERVICE_TYPE = 60015,
        DELETE_UTILITY_SERVICE_TYPE = 60016,

        SEARCH_UTILITY_COMPANY = 60017,
        GET_RECORD_BY_CODE_UTILITY_COMPANY = 60018,
        CREATE_UTILITY_COMPANY = 60019,
        UPDATE_UTILITY_COMPANY = 60020,

        SEARCH_UTILITY_SERVICE = 60021,
        GET_RECORD_BY_CODE_UTILITY_SERVICE = 60022,
        CREATE_UTILITY_SERVICE = 60023,
        UPDATE_UTILITY_SERVICE = 60024,

        SEARCH_UTIL_COMMISSION = 60025,
        GET_RECORD_BY_CODE_UTIL_COMMISSION = 60026,
        CREATE_UTIL_COMMISSION = 60027,
        UPDATE_UTIL_COMMISSION = 60028,

        SEARCH_UTIL_FEE = 60029,
        GET_RECORD_BY_CODE_UTIL_FEE = 60030,
        CREATE_UTIL_FEE = 60031,
        UPDATE_UTIL_FEE = 60032,

        SEARCH_UTILITY_CONSUMER = 60033,
        GET_RECORD_BY_CODE_UTILITY_CONSUMER = 60034,
        CREATE_UTILITY_CONSUMER = 60035,
        UPDATE_UTILITY_CONSUMER = 60036,
        GET_CUSTOMER_FOR_CONSUMER = 60037,

        SEARCH_UTILITY_DENOMINATION = 60038,
        GET_RECORD_BY_CODE_UTILITY_DENOMINATION = 60039,
        CREATE_UTILITY_DENOMINATION = 60040,
        DELETE_UTILITY_DENOMINATION = 60042,

        #endregion

        #region Addendum

        GET_ALL_ADDENDUM = 51001,
        GET_ADDENDUM_BY_CODE = 51002,
        SEARCH_ADDENDUM = 51003,
        GET_ALL_IRN_BY_USAGE_CODE = 51004,
        GET_USAGE_CODES = 51006,
        DELETE_ADDENDUM = 51007,
        GET_PDS_KEYS = 51008,
        UPDATE_ADDENDUM = 51009,

        #endregion

        #region Retrieval Request
        SEARCH_RETRIEVAL_REQUEST = 61000,
        GET_RETRIEVAL_REQUEST_SETUP_DATA = 61001,
        GET_RETRIEVAL_REQUEST_BY_CODE = 61002,
        DELETE_RETRIEVAL_REQUEST = 61003,
        CREATE_RETRIEVAL_REQUEST_REVERSAL = 61004,
        UPDATE_RETRIEVAL_REQUEST = 61005,
        CREATE_RETRIEVAL_REQUEST = 61006,
        #endregion

        #region Admin

        GET_ADMIN_BY_CODE = 51116,
        SEARCH_ADMIN = 51117,
        DELETE_ADMIN = 51118,
        UPDATE_ADMIN = 51119,
        GET_ADMIN_SETUP_DATA = 51120,
        CREATE_ADMIN = 51121,

        #endregion

        #region FirstChargeback

        GET_FIRST_CHARGEBACK_BY_CODE = 51102,
        SEARCH_FIRST_CHARGEBACK = 51103,
        GET_FIRST_CHARGEBACK_SETUP_DATA = 51104,
        CREATE_FIRST_CHARGEBACK = 51105,
        DELETE_FIRST_CHARGEBACK = 51106,
        GET_ALL_MESSAGE_REASONS_BY_FUNCTION_CODE = 51107,
        UPDATE_FIRST_CHARGEBACK = 51108,
        CREATE_REVERSAL = 51122,
        #endregion

        #region ArbitrationChargeback

        GET_ARBITRATION_CHARGEBACK_BY_CODE = 51109,
        SEARCH_ARBITRATION_CHARGEBACK = 51110,
        GET_ARBITRATION_CHARGEBACK_SETUP_DATA = 51111,
        CREATE_ARBITRATION_CHARGEBACK = 51112,
        DELETE_ARBITRATION_CHARGEBACK = 51113,
        GET_ALL_MESSAGE_REASONS_BY_FUNCTION_CODE_ARBITRATION = 51114,
        UPDATE_ARBITRATION_CHARGEBACK = 51115,
        CREATE_REVERSAL_ARBITRATION = 51122,
        #endregion

        #region Export

        GET_EXPORT_BY_CODE = 51124,
        SEARCH_EXPORT = 51125,
        GET_EXPORT_SETUP_DATA = 51126,
        CREATE_EXPORT = 51127,

        #endregion


        #region Fee Collection
        SEARCH_FEE_COLLECTION = 61007,
        GET_FEE_COLLECTION_SETUP_DATA = 61008,
        GET_FEE_COLLECTION_BY_CODE = 61009,
        DELETE_FEE_COLLECTION = 61010,
        CREATE_FEE_COLLECTION_REVERSAL = 61011,
        UPDATE_FEE_COLLECTION = 61012,
        CREATE_FEE_COLLECTION = 61013,
        CREATE_FEE_COLLECTION_RETURN = 61014,
        #endregion

        #region Visa Card Settlement

        #region Settlement
        GET_VISA_SETTLEMENT_SETUP_DATA = 71000,
        SEARCH_VISA_SETTLEMENT = 71001,
        GET_VISA_SETTLEMENT_FORM_SETUP_DATA = 71002,
        GET_VISA_SETTLEMENT_BY_CODE = 71003,
        SEARCH_VISA_TRANSACTION_FOR_LINK = 71004,
        FORC_MATCH_VISA_SETTLEMENT = 71005,
        MARK_PROCESSED_VISA_MESSAGE = 71006,
        POST_VISA_SETTLEMET = 71007,
        #endregion

        #region Retrival Copy
        GET_VISA_RETRIVAL_SETUP_DATA = 71010,
        SEARCH_VISA_RETRIVAL = 71011,
        GET_VISA_RETRIVAL_FORM_SETUP_DATA = 71012,
        GET_VISA_RETRIVAL_BY_CODE = 71013,
        GET_VISA_RETRIVAL_PARENT_BY_CODE = 71014,
        CREATE_VISA_RETRIVAL = 71015,
        #endregion

        #region Chargeback
        GET_VISA_CHARGEBACK_SETUP_DATA = 71020,
        SEARCH_VISA_CHARGEBACK = 71021,
        GET_VISA_CHARGEBACK_FORM_SETUP_DATA = 71022,
        GET_VISA_CHARGEBACK_BY_CODE = 71023,
        GET_VISA_CHARGEBACK_PARENT_BY_CODE = 71024,
        CREATE_VISA_CHARGEBACK = 71025,
        UPDATE_VISA_CHARGEBACK = 71026,
        CREATE_VISA_CHARGEBACK_REVERSAL = 71027,
        #endregion




        #region Text Message
        GET_VISA_TEXT_MESSAGE_SETUP_DATA = 91007,
        SEARCH_VISA_TEXT_MESSAGE = 91008,
        GET_VISA_TEXT_MESSAGE_BY_CODE = 91009,
        CREATE_VISA_TEXT_MESSAGE = 91010,
        UPDATE_VISA_TEXT_MESSAGE = 91011,
        DELETE_VISA_TEXT_MESSAGE = 91012,
        GET_VISA_TEXT_MESSAGE_FORM_SETUP_DATA = 91013,
        #endregion

        #region Fee Collection

        GET_VISA_FEE_COLLECTION_SETUP_DATA = 71050,
        SEARCH_VISA_FEE_COLLECTION = 71051,
        GET_VISA_FEE_COLLECTION_BY_CODE = 71052,
        CREATE_VISA_FEE_COLLECTION = 71053,
        UPDATE_VISA_FEE_COLLECTION = 71054,
        DELETE_VISA_FEE_COLLECTION = 71055,
        POST_VISA_FEE_COLLECTION = 71056,
        GET_VISA_FEE_COLLECTION_FORM_SETUP_DATA = 71057,
        #endregion


        #region Representment
        GET_VISA_REPRESENTMENT_SETUP_DATA = 71030,
        SEARCH_VISA_REPRESENTMENT = 71031,
        GET_VISA_REPRESENTMENT_FORM_SETUP_DATA = 71032,
        GET_VISA_REPRESENTMENT_BY_CODE = 71033,
        CREATE_VISA_REPRESENTMENT = 71035,
        UPDATE_VISA_REPRESENTMENT = 71036,
        POST_VISA_REPRESENTMENT = 71037,
        CREATE_VISA_ARBITRATION = 71038,
        CREATE_VISA_PRE_ARBITRATION = 71039,
        #endregion

        #region Chargeback Reversal 

        UPDATE_VISA_CHARGEBACK_REV = 91032,
        #endregion

        #region Stip
        GET_VISA_STIP_SETUP_DATA = 71060,
        SEARCH_VISA_STIP = 71061,
        GET_VISA_STIP_BY_CODE = 71062,
        MARKED_PROCESSED_VISA_STIP = 71063,
        #endregion


        #region Visa Export
        GET_VISA_EXPORT_SETUP_DATA = 71070,
        SEARCH_VISA_EXPORT = 71071,
        PROCESS_VISA_EXPORT = 71072,
        #endregion        #endregion
        #region Funds disbursement

        GET_VISA_FUNDS_DISBURSEMENT_SETUP_DATA = 92050,
        SEARCH_VISA_FUNDS_DISBURSEMENT = 92051,
        GET_VISA_FUNDS_DISBURSEMENT_BY_CODE = 92052,
        CREATE_VISA_FUNDS_DISBURSEMENT = 92053,
        UPDATE_VISA_FUNDS_DISBURSEMENT = 92054,
        DELETE_VISA_FUNDS_DISBURSEMENT = 92055,
        POST_VISA_FUNDS_DISBURSEMENT = 92056,
        GET_VISA_FUNDS_DISBURSEMENT_FORM_SETUP_DATA = 92057,
        #endregion
        #region Fraud Tracking

        GET_VISA_FRAUD_TRACKING_SETUP_DATA = 93050,
        SEARCH_VISA_FRAUD_TRACKING = 93051,
        GET_VISA_FRAUD_TRACKING_BY_CODE = 93052,
        CREATE_VISA_FRAUD_TRACKING = 93053,
        UPDATE_VISA_FRAUD_TRACKING = 93054,
        DELETE_VISA_FRAUD_TRACKING = 93055,
        POST_VISA_FRAUD_TRACKING = 93056,
        GET_VISA_FRAUD_TRACKING_FORM_SETUP_DATA = 93057,
        #endregion
        #region ChargebackTracking
        GET_VISA_CHARGEBACK_SETUP_DATA_FOR_TRACKING = 71040,
        SEARCH_VISA_CHARGEBACK_FOR_TRACKING = 71041,
        GET_VISA_CHARGEBACK_FORM_SETUP_DATA_TRACKING = 71042,
        GET_VISA_CHARGEBACK_BY_CODE_TRACKING = 71043,
        GET_VISA_CHARGEBACK_PARENT_BY_CODE_TRACKING = 71044,
        CREATE_VISA_CHARGEBACK_TRACKING = 71045,
        UPDATE_VISA_CHARGEBACK_TRACKING = 71046,
        CREATE_VISA_CHARGEBACK_REVERSAL_TRACKING = 71047,
        #endregion
        #endregion

    }
}
