//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyUser
    {
        public string CompanyUserLoginID { get; set; }
        public string CompanyUserPassword { get; set; }
        public string CompanyUserName { get; set; }
        public string CompanyUserPhone { get; set; }
        public string CompanyUserEmail { get; set; }
        public string CompanyUserStatus { get; set; }
        public Nullable<System.Guid> UserRoleID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
