//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentSchedule
    {
        public System.Guid EquipmentScheduleID { get; set; }
        public string EquipmentScheduleName { get; set; }
        public string EquipmentScheduleType { get; set; }
        public string EquipmentScheduleBasis { get; set; }
        public string InspectionDuration { get; set; }
        public Nullable<System.DateTime> LastInspectionDate { get; set; }
        public Nullable<System.DateTime> NextInspectionDate { get; set; }
        public Nullable<int> Margin { get; set; }
        public Nullable<int> Leverage { get; set; }
        public Nullable<int> Interval { get; set; }
        public Nullable<System.Guid> EquipmentID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
