//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.EquipmentSchedule = new HashSet<EquipmentSchedule>();
        }
    
        public System.Guid EquipmentID { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentType { get; set; }
        public string EquipmentModel { get; set; }
        public string EquipmentMake { get; set; }
        public string EquipmentRange { get; set; }
        public string EquipmentAccuracy { get; set; }
        public string EquipmentOthers { get; set; }
        public string EquipmentCustodian { get; set; }
        public string EquipmentLocation { get; set; }
        public string EquipmentFamilyName { get; set; }
        public string AssetID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.Guid> EquipmentCategoryID { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentSchedule> EquipmentSchedule { get; set; }
        public virtual EquipmentCategory EquipmentCategory { get; set; }
    }
}
