//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTransferRequest
    {
        public long ATRequestID { get; set; }
        public System.Guid SourceRig { get; set; }
        public System.Guid DestinationRig { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> RequestSequenceID { get; set; }
        public Nullable<bool> IsTransfered { get; set; }
        public string SourceENode { get; set; }
        public string DestinationENode { get; set; }
        public Nullable<int> EstimatedDeliveryDay { get; set; }
        public bool IsCountryBounded { get; set; }
        public int InitiatedByLevel { get; set; }
        public long TransferNumber { get; set; }
        public string ATRUniqueNumber { get; set; }
    }
}
