//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRLevelBasePriority
    {
        public long ID { get; set; }
        public long ATRequestID { get; set; }
        public System.Guid OrgRoleID { get; set; }
        public int Level { get; set; }
        public int Priority { get; set; }
        public bool IsIgnored { get; set; }
        public bool IsProcessed { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string LoginID { get; set; }
    }
}
