//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRRoutingLog
    {
        public int ID { get; set; }
        public long ATRequestID { get; set; }
        public int UserNotificationTypeID { get; set; }
        public Nullable<bool> IsRouted { get; set; }
        public string EmailUser { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<System.Guid> OrgRoleID { get; set; }
        public string Comments { get; set; }
    }
}
