//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRRoutingLogAction
    {
        public long ID { get; set; }
        public long ATRequestID { get; set; }
        public string UserName { get; set; }
        public string Country { get; set; }
        public string RoleName { get; set; }
        public string Action { get; set; }
        public string Comments { get; set; }
        public string ActionDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}
