//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRRoutingLevel
    {
        public int ATRRoutingLevelID { get; set; }
        public string Describer { get; set; }
        public int Level { get; set; }
        public Nullable<System.Guid> OrgRoleID { get; set; }
        public bool CanSetNextLevelRoute { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public bool IsParentForNextLevels { get; set; }
        public int Priority { get; set; }
    }
}
