//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRUserDefinedRouting
    {
        public int ATRUserDefinedRoutingID { get; set; }
        public long ATRequestID { get; set; }
        public int Level { get; set; }
        public Nullable<System.Guid> OrgRoleID { get; set; }
        public string UsersList { get; set; }
        public bool IsProcessed { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}
