//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_Requests
    {
        public System.Guid BD_RequestID { get; set; }
        public Nullable<System.Guid> RigID { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    }
}
