//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_RigEqDoc
    {
        public System.Guid BD_RigDocDetailsID { get; set; }
        public Nullable<System.Guid> BD_ReqDetailsID { get; set; }
        public string DocName { get; set; }
        public Nullable<System.Guid> DocType { get; set; }
        public string CertNumber { get; set; }
        public Nullable<System.DateTime> CertDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public byte[] DocFile { get; set; }
    }
}
