//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkAddLog
    {
        public short id { get; set; }
        public string filename { get; set; }
        public Nullable<int> TotalRecords { get; set; }
        public Nullable<int> FailedRecords { get; set; }
        public Nullable<int> Duplicated { get; set; }
        public Nullable<int> InvalidChild { get; set; }
        public Nullable<int> InvalidAssetID { get; set; }
        public Nullable<int> RigNameMissing { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string OperationType { get; set; }
    }
}
