//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConflictingPMServiceFormDefination
    {
        public System.Guid PMServiceFormDefinitionID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.Guid> OrgunitID { get; set; }
        public int ConflictingID { get; set; }
        public Nullable<System.Guid> PMServiceFormId { get; set; }
    }
}
