//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyLog
    {
        public System.Guid DailyLogID { get; set; }
        public string WorkSummary { get; set; }
        public Nullable<System.DateTime> DailyLogDate { get; set; }
        public string LoggedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string LoginID { get; set; }
        public Nullable<System.Guid> OrgUnitId { get; set; }
    
        public virtual SecUser SecUser { get; set; }
    }
}
