//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyLogBOPPressure
    {
        public System.Guid DailyLogPressureID { get; set; }
        public Nullable<System.DateTime> BOPPressureLogDate { get; set; }
        public string AccuPressureUnit { get; set; }
        public string AccuPressureFloor { get; set; }
        public string AccuPressureRemote { get; set; }
        public string ManiPressureUnit { get; set; }
        public string ManiPressureFloor { get; set; }
        public string ManiPressureRemote { get; set; }
        public string AnnuPressureUnit { get; set; }
        public string AnnuPressureFloor { get; set; }
        public string AnnuPressureRemote { get; set; }
        public Nullable<System.Guid> OrgUnitID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual OrgUnit OrgUnit { get; set; }
    }
}
