//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyActivityReportDetails
    {
        public System.Guid DailyActivityReportDetailID { get; set; }
        public System.Guid DailyActivityReportID { get; set; }
        public int DailyActivityReportDetailCategoryID { get; set; }
        public string FirstColumn { get; set; }
        public Nullable<decimal> HoursDown { get; set; }
        public string SMO { get; set; }
        public Nullable<int> DaysOverDue { get; set; }
        public string SAPNumber { get; set; }
        public Nullable<System.Guid> RigEquipmentScheduleJobsID { get; set; }
        public Nullable<System.Guid> PMServiceFormID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOnDate { get; set; }
        public string ComputerID { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> MiscDate { get; set; }
        public string PMFormName { get; set; }
        public string SMOStatus { get; set; }
        public Nullable<int> UniqueID { get; set; }
        public Nullable<System.Guid> RigEquipmentID { get; set; }
    
        public virtual DailyActivityReport DailyActivityReport { get; set; }
    }
}
