//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyActivityReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DailyActivityReport()
        {
            this.DailyActivityReportDetails = new HashSet<DailyActivityReportDetails>();
        }
    
        public System.Guid DailyActivityReportID { get; set; }
        public string WorkDoneLast24Hrs { get; set; }
        public string PlannedJobNext24Hrs { get; set; }
        public System.DateTime ReportDate { get; set; }
        public System.Guid RoleID { get; set; }
        public System.Guid OrgUnitID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOnDate { get; set; }
        public string ComputerID { get; set; }
    
        public virtual OrgRole OrgRole { get; set; }
        public virtual OrgUnit OrgUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyActivityReportDetails> DailyActivityReportDetails { get; set; }
    }
}
