//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataImportHistory
    {
        public System.Guid DataImportID { get; set; }
        public System.Guid OrgUnitID { get; set; }
        public string LoginID { get; set; }
        public System.DateTime ImportedOn { get; set; }
        public string FilePath { get; set; }
        public bool IsExport { get; set; }
        public string DataBackupOn { get; set; }
    
        public virtual OrgUnit OrgUnit { get; set; }
    }
}
