//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dec14_PMServiceForms
    {
        public System.Guid PMServiceFormID { get; set; }
        public Nullable<System.Guid> RigEquipmentID { get; set; }
        public System.Guid PMServiceFormDefinitionID { get; set; }
        public Nullable<System.DateTime> PMServiceDate { get; set; }
        public string PMServiceHours { get; set; }
        public string Comments { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}
