//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentSchedule()
        {
            this.RigEquipmentSchedule = new HashSet<RigEquipmentSchedule>();
            this.RigEquipmentSchedule1 = new HashSet<RigEquipmentSchedule>();
            this.RigEquipmentSchedule2 = new HashSet<RigEquipmentSchedule>();
            this.PMServiceFormDefinition = new HashSet<PMServiceFormDefinition>();
        }
    
        public System.Guid EquipmentScheduleId { get; set; }
        public Nullable<System.Guid> EquipmentID { get; set; }
        public Nullable<System.Guid> ScheduleBasisId { get; set; }
        public Nullable<System.Guid> ScheduleTypeId { get; set; }
        public string EquipmentScheduleName { get; set; }
        public Nullable<int> RecurranceMeterHours { get; set; }
        public Nullable<int> RecurranceCalendarValue { get; set; }
        public Nullable<int> CalendarAlertMargin { get; set; }
        public Nullable<int> CalendarEscalationMargin { get; set; }
        public Nullable<int> MeterAlertMargin { get; set; }
        public Nullable<int> MeterEscalationMargin { get; set; }
        public Nullable<bool> IsScheduleSuspended { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> CertificateRequired { get; set; }
        public Nullable<int> ScheduleActivationType { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Equipment Equipment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigEquipmentSchedule> RigEquipmentSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigEquipmentSchedule> RigEquipmentSchedule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigEquipmentSchedule> RigEquipmentSchedule2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMServiceFormDefinition> PMServiceFormDefinition { get; set; }
        public virtual ScheduleBasis ScheduleBasis { get; set; }
        public virtual ScheduleBasis ScheduleBasis1 { get; set; }
        public virtual ScheduleType ScheduleType { get; set; }
        public virtual ScheduleType ScheduleType1 { get; set; }
    }
}
