//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentTemp
    {
        public System.Guid EquipmentID { get; set; }
        public Nullable<System.Guid> AssetGroupID { get; set; }
        public Nullable<System.Guid> EquipmentCriticalityId { get; set; }
        public Nullable<System.Guid> EquipmentCategoryID { get; set; }
        public Nullable<System.Guid> EquipmentSpecsCategoryID { get; set; }
        public Nullable<System.Guid> EquipmentParentID { get; set; }
        public string EquipmentName { get; set; }
        public string Make { get; set; }
        public string FamilyName { get; set; }
        public string Model { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string Description { get; set; }
        public bool HasHourMeter { get; set; }
        public string HasValveType { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsAsset { get; set; }
        public Nullable<decimal> WBSSequence { get; set; }
        public string WBSSequencetext { get; set; }
        public Nullable<bool> IsTagable { get; set; }
    }
}
