//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.PMServiceFormDefinition = new HashSet<PMServiceFormDefinition>();
            this.EquipmentSchedule = new HashSet<EquipmentSchedule>();
            this.EquipmentDocument = new HashSet<EquipmentDocument>();
            this.RigEquipment = new HashSet<RigEquipment>();
            this.EquipmentSchedule1 = new HashSet<EquipmentSchedule>();
            this.EquipmentSpecification = new HashSet<EquipmentSpecification>();
            this.EquipmentOneTimeJobs = new HashSet<EquipmentOneTimeJobs>();
        }
    
        public System.Guid EquipmentID { get; set; }
        public Nullable<System.Guid> AssetGroupID { get; set; }
        public Nullable<System.Guid> EquipmentCriticalityId { get; set; }
        public Nullable<System.Guid> EquipmentCategoryID { get; set; }
        public Nullable<System.Guid> EquipmentSpecsCategoryID { get; set; }
        public Nullable<System.Guid> EquipmentParentID { get; set; }
        public string EquipmentName { get; set; }
        public string Make { get; set; }
        public string FamilyName { get; set; }
        public string Model { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string Description { get; set; }
        public bool HasHourMeter { get; set; }
        public string HasValveType { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsAsset { get; set; }
        public Nullable<decimal> WBSSequence { get; set; }
        public string WBSSequencetext { get; set; }
        public Nullable<bool> IsTagable { get; set; }
        public string TagNStampingLocation { get; set; }
        public Nullable<bool> COCNo { get; set; }
        public Nullable<bool> CALIBRIONNo { get; set; }
        public Nullable<bool> INSPECTNo { get; set; }
        public Nullable<bool> PRESSURENo { get; set; }
        public Nullable<bool> LOADTESTNo { get; set; }
        public Nullable<bool> CATIIINo { get; set; }
        public Nullable<bool> CATIVNo { get; set; }
        public Nullable<bool> COC { get; set; }
        public Nullable<bool> CALIBRION { get; set; }
        public Nullable<bool> INSPECT { get; set; }
        public Nullable<bool> PRESSURE { get; set; }
        public Nullable<bool> LOADTEST { get; set; }
        public Nullable<bool> CATIII { get; set; }
        public Nullable<bool> CATIV { get; set; }
        public bool IsKeyEquipment { get; set; }
    
        public virtual AssetGroup AssetGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMServiceFormDefinition> PMServiceFormDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentSchedule> EquipmentSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentDocument> EquipmentDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigEquipment> RigEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentSchedule> EquipmentSchedule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentSpecification> EquipmentSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentOneTimeJobs> EquipmentOneTimeJobs { get; set; }
        public virtual EquipmentCategory EquipmentCategory { get; set; }
        public virtual EquipmentCriticality EquipmentCriticality { get; set; }
        public virtual EquipmentSpecsCategory EquipmentSpecsCategory { get; set; }
    }
}
