//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentTransferHistoryLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentTransferHistoryLog()
        {
            this.RigEquipmentTransferDetails = new HashSet<RigEquipmentTransferDetails>();
        }
    
        public System.Guid EquipmentTransferHistoryLogID { get; set; }
        public System.Guid OrgUnitID { get; set; }
        public System.Guid ToOrgUnitID { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string Comments { get; set; }
        public string TransferredBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public int Transferno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigEquipmentTransferDetails> RigEquipmentTransferDetails { get; set; }
        public virtual OrgUnit OrgUnit { get; set; }
        public virtual OrgUnit OrgUnit1 { get; set; }
    }
}
