//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExRegisterDetailsCopy
    {
        public System.Guid ExRegisterDetailsID { get; set; }
        public System.Guid ExRegisterID { get; set; }
        public System.Guid RigEquipmentID { get; set; }
        public Nullable<int> Tag { get; set; }
        public Nullable<int> OldTag { get; set; }
        public string CircuitID { get; set; }
        public string Serial { get; set; }
        public string Certification { get; set; }
        public string Protection { get; set; }
        public string IP { get; set; }
        public string Location { get; set; }
        public string GridRef { get; set; }
        public string Classification { get; set; }
        public string Drawing { get; set; }
        public string Rev { get; set; }
        public string SheetType { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOnDate { get; set; }
        public System.Guid OrgUnitID { get; set; }
        public Nullable<bool> IsDeletedFlag { get; set; }
        public string RigEquipmentName { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
    }
}
