//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetCoordinates
    {
        public System.Guid OrgUnitID { get; set; }
        public string OrgNamePrm { get; set; }
        public decimal FromLatDeg { get; set; }
        public decimal FromLatMin { get; set; }
        public decimal FromLatSec { get; set; }
        public decimal ToLatDeg { get; set; }
        public decimal ToLatMin { get; set; }
        public decimal ToLatSec { get; set; }
        public decimal FromLongDeg { get; set; }
        public decimal FromLongMin { get; set; }
        public decimal FromLongSec { get; set; }
        public decimal ToLongDeg { get; set; }
        public decimal ToLongMin { get; set; }
        public decimal ToLongSec { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}
