//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IACDCodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IACDCodes()
        {
            this.MorningReportOperations = new HashSet<MorningReportOperations>();
        }
    
        public System.Guid IACDCodeID { get; set; }
        public int IACDCode { get; set; }
        public string IACDCodeDescription { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> ComboCategoryCode { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string IACDCodeDescriptionruRu { get; set; }
        public string IACDCodeDescriptionesEs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MorningReportOperations> MorningReportOperations { get; set; }
    }
}
