//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImprovementCommitment_bk
    {
        public System.Guid ImprovementCommitmentID { get; set; }
        public string ICRNo { get; set; }
        public System.DateTime DateRaised { get; set; }
        public Nullable<System.Guid> OrgUnitID { get; set; }
        public string ImprovementCommitmentSource { get; set; }
        public string OpportunityForImprovement { get; set; }
        public string RaisedBy { get; set; }
        public string CorrectiveAction { get; set; }
        public string CorrectiveActionBy { get; set; }
        public Nullable<System.DateTime> CorrectiveTargetDate { get; set; }
        public Nullable<bool> CorrectiveActionCompleted { get; set; }
        public string CorrectiveActionComments { get; set; }
        public Nullable<System.DateTime> CorrectiveActionCompletionDate { get; set; }
        public string PreventiveAction { get; set; }
        public string PreventiveActionBy { get; set; }
        public Nullable<System.DateTime> PreventiveActionTargetDate { get; set; }
        public Nullable<bool> PreventiveActionCompleted { get; set; }
        public string PreventiveActionComments { get; set; }
        public Nullable<System.DateTime> PreventiveActionCompletionDate { get; set; }
        public string FollowUpCorrectiveAction { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<double> PriceOfICR { get; set; }
        public Nullable<System.DateTime> CloseOutDate { get; set; }
        public string ApprovedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.Guid> CorrectiveActionByRoleID { get; set; }
        public Nullable<System.Guid> PreventiveActionByRoleID { get; set; }
        public string BMSStandardReference { get; set; }
        public Nullable<int> icrNo1 { get; set; }
    }
}
