//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiftingGearRegisterDetails
    {
        public System.Guid LiftingGearRegisterDetailsID { get; set; }
        public System.Guid LiftingGearRegisterID { get; set; }
        public string EntryID { get; set; }
        public string Description { get; set; }
        public string CertNo { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DatePlacedInService { get; set; }
        public Nullable<System.DateTime> LastInspection { get; set; }
        public Nullable<System.DateTime> NextInspection { get; set; }
        public string PONo { get; set; }
        public Nullable<System.DateTime> DateRemovedFromService { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string SAPNo { get; set; }
        public string Manufacturer { get; set; }
        public string SWL { get; set; }
    
        public virtual LiftingGearRegister LiftingGearRegister { get; set; }
    }
}
