//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialTransferDetails
    {
        public System.Guid MaterialTransferDetailsID { get; set; }
        public System.Guid MaterialTransferHistoryLogID { get; set; }
        public Nullable<System.Guid> RigEquipmentID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOnDate { get; set; }
        public bool IsReceived { get; set; }
        public string Miscellaneous { get; set; }
    
        public virtual MaterialTransferHistoryLog MaterialTransferHistoryLog { get; set; }
        public virtual RigEquipment RigEquipment { get; set; }
    }
}
