//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiscellaneousRigEquipmentAttribute
    {
        public System.Guid MiscellaneousRigEquipmentAttributeID { get; set; }
        public System.Guid MiscellaneousRigEquipmentID { get; set; }
        public System.Guid CompanyAttributeID { get; set; }
        public string AttributeValue { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
