//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiscellaneousRigEquipmentDocumentAttribute
    {
        public System.Guid MiscellaneousRigEquipmentDocumentAttributeID { get; set; }
        public System.Guid MiscellaneousRigEquipmentDocumentID { get; set; }
        public System.Guid CompanyMiscellaneousRigEquipmentDocumentAttributeID { get; set; }
        public string DocumentAttributeValue { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
