//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MorningReportSchedule
    {
        public System.Guid RigID { get; set; }
        public string RigNewStatus { get; set; }
        public string RigOldStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool IsProcess { get; set; }
        public int MorningReportScheduleID { get; set; }
    }
}
