//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MorningReportTrainings
    {
        public System.Guid TrainingsID { get; set; }
        public System.Guid MorningReportID { get; set; }
        public Nullable<System.DateTime> TrainingDate { get; set; }
        public Nullable<int> NoOfTrainees { get; set; }
        public Nullable<int> TrainingDuration { get; set; }
        public string TrainingTitle { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
    
        public virtual MorningReport MorningReport { get; set; }
    }
}
