//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MR_FuelUsageDetails
    {
        public Nullable<int> RigUsed { get; set; }
        public Nullable<int> CampUsed { get; set; }
        public string RigName { get; set; }
        public System.Guid OrgUnitID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<decimal> HourlyConsumptionRigUsed { get; set; }
        public Nullable<decimal> HourlyConsumptionCampUsed { get; set; }
        public int IACDCode { get; set; }
        public string IACDCodeDescription { get; set; }
        public string RigStatus { get; set; }
        public string OperationFrom1 { get; set; }
        public string OperationTo1 { get; set; }
        public Nullable<decimal> OperationHours { get; set; }
        public string OperationDetails { get; set; }
    }
}
