//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OilInventory
    {
        public System.Guid OilInventoryID { get; set; }
        public Nullable<System.Guid> OrgUnitID { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public string EngineOilSynthetic { get; set; }
        public string EngineOilMineral { get; set; }
        public string GearOilSynthetic { get; set; }
        public string GearOilMineral { get; set; }
        public string ChainOil { get; set; }
        public string CompressorOil { get; set; }
        public string HydraulicOil { get; set; }
        public string GreaseTubes { get; set; }
        public string Nalcool { get; set; }
        public string TBNImprover { get; set; }
        public string CyprinaGrease { get; set; }
        public string GreasePails { get; set; }
        public string ExtraName1 { get; set; }
        public string ExtraValue1 { get; set; }
        public string ExtraName2 { get; set; }
        public string ExtraValue2 { get; set; }
        public string ExtraName3 { get; set; }
        public string ExtraValue3 { get; set; }
        public string ExtraName4 { get; set; }
        public string ExtraValue4 { get; set; }
        public string ExtraName5 { get; set; }
        public string ExtraValue5 { get; set; }
        public string ExtraName6 { get; set; }
        public string ExtraValue6 { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual OrgUnit OrgUnit { get; set; }
    }
}
