//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrgUnit()
        {
            this.CalibrationRegister = new HashSet<CalibrationRegister>();
            this.ClientSynchronizations = new HashSet<ClientSynchronizations>();
            this.DailyActivityReport = new HashSet<DailyActivityReport>();
            this.DailyLogBOPPressure = new HashSet<DailyLogBOPPressure>();
            this.DataImportHistory = new HashSet<DataImportHistory>();
            this.EquipmentTransferHistoryLog = new HashSet<EquipmentTransferHistoryLog>();
            this.EquipmentTransferHistoryLog1 = new HashSet<EquipmentTransferHistoryLog>();
            this.ExRegister = new HashSet<ExRegister>();
            this.ExRegisterDetailsUpdate = new HashSet<ExRegisterDetailsUpdate>();
            this.LiftingGearRegister = new HashSet<LiftingGearRegister>();
            this.MaterialTransferHistoryLog = new HashSet<MaterialTransferHistoryLog>();
            this.MaterialTransferHistoryLog1 = new HashSet<MaterialTransferHistoryLog>();
            this.MorningReport = new HashSet<MorningReport>();
            this.OilInventory = new HashSet<OilInventory>();
            this.ToDoList = new HashSet<ToDoList>();
            this.RigStatusLog = new HashSet<RigStatusLog>();
            this.RigEquipment = new HashSet<RigEquipment>();
            this.RigEquipment_1 = new HashSet<RigEquipment_1>();
            this.PressureVesselRegister = new HashSet<PressureVesselRegister>();
            this.ReleifValveRegister = new HashSet<ReleifValveRegister>();
            this.RamsAlert = new HashSet<RamsAlert>();
            this.OrgUserRole = new HashSet<OrgUserRole>();
            this.RigEquipmentOneTimeJob = new HashSet<RigEquipmentOneTimeJob>();
        }
    
        public System.Guid OrgUnitID { get; set; }
        public Nullable<System.Guid> ParentOrgID { get; set; }
        public System.Guid UnitTypeID { get; set; }
        public string OrgNamePrm { get; set; }
        public string OrgNameSec { get; set; }
        public string OrgFullName { get; set; }
        public decimal HierarchyLevel { get; set; }
        public string OtherCode1 { get; set; }
        public string OtherCode2 { get; set; }
        public string OtherCode3 { get; set; }
        public string OrgAddress { get; set; }
        public string OrgPhone { get; set; }
        public string OrgFax { get; set; }
        public string OrgEmail { get; set; }
        public string OrgShortName { get; set; }
        public string OrgShortNameSec { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalibrationRegister> CalibrationRegister { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSynchronizations> ClientSynchronizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyActivityReport> DailyActivityReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyLogBOPPressure> DailyLogBOPPressure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataImportHistory> DataImportHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentTransferHistoryLog> EquipmentTransferHistoryLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentTransferHistoryLog> EquipmentTransferHistoryLog1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExRegister> ExRegister { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExRegisterDetailsUpdate> ExRegisterDetailsUpdate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiftingGearRegister> LiftingGearRegister { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialTransferHistoryLog> MaterialTransferHistoryLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialTransferHistoryLog> MaterialTransferHistoryLog1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MorningReport> MorningReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OilInventory> OilInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToDoList> ToDoList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigStatusLog> RigStatusLog { get; set; }
        public virtual RigDetails RigDetails { get; set; }
        public virtual RigDetails RigDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigEquipment> RigEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigEquipment_1> RigEquipment_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PressureVesselRegister> PressureVesselRegister { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleifValveRegister> ReleifValveRegister { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RamsAlert> RamsAlert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgUserRole> OrgUserRole { get; set; }
        public virtual RigDetails RigDetails2 { get; set; }
        public virtual OrgUnitType OrgUnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigEquipmentOneTimeJob> RigEquipmentOneTimeJob { get; set; }
    }
}
