//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMDiagramValue
    {
        public System.Guid PMDiagramValueID { get; set; }
        public Nullable<System.Guid> PMServiceFormID { get; set; }
        public System.Guid PMServiceFormSectionDiagramsID { get; set; }
        public Nullable<System.Guid> ColorCodeID { get; set; }
        public Nullable<bool> BoolVal1 { get; set; }
        public Nullable<bool> BoolVal2 { get; set; }
        public Nullable<bool> BoolVal3 { get; set; }
        public Nullable<bool> BoolVal4 { get; set; }
        public Nullable<bool> BoolVal5 { get; set; }
        public Nullable<bool> BoolVal6 { get; set; }
        public Nullable<bool> BoolVal7 { get; set; }
        public Nullable<bool> BoolVal8 { get; set; }
        public Nullable<bool> BoolVal9 { get; set; }
        public Nullable<bool> BoolVal10 { get; set; }
        public Nullable<int> IntVal1 { get; set; }
        public Nullable<int> IntVal2 { get; set; }
        public Nullable<int> IntVal3 { get; set; }
        public Nullable<int> IntVal4 { get; set; }
        public Nullable<int> IntVal5 { get; set; }
        public Nullable<int> IntVal6 { get; set; }
        public Nullable<int> IntVal7 { get; set; }
        public Nullable<int> IntVal8 { get; set; }
        public Nullable<int> IntVal9 { get; set; }
        public Nullable<int> IntVal10 { get; set; }
        public Nullable<int> IntVal11 { get; set; }
        public Nullable<int> IntVal12 { get; set; }
        public Nullable<int> IntVal13 { get; set; }
        public Nullable<int> IntVal14 { get; set; }
        public Nullable<int> IntVal15 { get; set; }
        public Nullable<int> IntVal16 { get; set; }
        public Nullable<int> IntVal17 { get; set; }
        public Nullable<int> IntVal18 { get; set; }
        public Nullable<int> IntVal19 { get; set; }
        public Nullable<int> IntVal20 { get; set; }
        public Nullable<double> DblVal1 { get; set; }
        public Nullable<double> DblVal2 { get; set; }
        public Nullable<double> DblVal3 { get; set; }
        public Nullable<double> DblVal4 { get; set; }
        public Nullable<double> DblVal5 { get; set; }
        public Nullable<double> DblVal6 { get; set; }
        public Nullable<double> DblVal7 { get; set; }
        public Nullable<double> DblVal8 { get; set; }
        public Nullable<double> DblVal9 { get; set; }
        public Nullable<double> DblVal10 { get; set; }
        public Nullable<double> DblVal11 { get; set; }
        public Nullable<double> DblVal12 { get; set; }
        public Nullable<double> DblVal13 { get; set; }
        public Nullable<double> DblVal14 { get; set; }
        public Nullable<double> DblVal15 { get; set; }
        public Nullable<double> DblVal16 { get; set; }
        public Nullable<double> DblVal17 { get; set; }
        public Nullable<double> DblVal18 { get; set; }
        public Nullable<double> DblVal19 { get; set; }
        public Nullable<double> DblVal20 { get; set; }
        public Nullable<double> DblVal21 { get; set; }
        public Nullable<double> DblVal22 { get; set; }
        public Nullable<double> DblVal23 { get; set; }
        public Nullable<double> DblVal24 { get; set; }
        public Nullable<double> DblVal25 { get; set; }
        public Nullable<double> DblVal26 { get; set; }
        public Nullable<double> DblVal27 { get; set; }
        public Nullable<double> DblVal28 { get; set; }
        public Nullable<double> DblVal29 { get; set; }
        public Nullable<double> DblVal30 { get; set; }
        public string StrVal1 { get; set; }
        public string StrVal2 { get; set; }
        public string StrVal3 { get; set; }
        public string StrVal4 { get; set; }
        public string StrVal5 { get; set; }
        public string StrVal6 { get; set; }
        public string StrVal7 { get; set; }
        public string StrVal8 { get; set; }
        public string StrVal9 { get; set; }
        public string StrVal10 { get; set; }
        public string StrVal11 { get; set; }
        public string StrVal12 { get; set; }
        public string StrVal13 { get; set; }
        public string StrVal14 { get; set; }
        public string StrVal15 { get; set; }
        public string StrVal16 { get; set; }
        public string StrVal17 { get; set; }
        public string StrVal18 { get; set; }
        public string StrVal19 { get; set; }
        public string StrVal20 { get; set; }
        public string StrVal21 { get; set; }
        public string StrVal22 { get; set; }
        public string StrVal23 { get; set; }
        public string StrVal24 { get; set; }
        public string StrVal25 { get; set; }
        public string StrVal26 { get; set; }
        public string StrVal27 { get; set; }
        public string StrVal28 { get; set; }
        public string StrVal29 { get; set; }
        public string StrVal30 { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual PMServiceForms PMServiceForms { get; set; }
        public virtual PMServiceFormSectionDiagrams PMServiceFormSectionDiagrams { get; set; }
    }
}
