//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMProcedureFields
    {
        public System.Guid PMProcedureFieldsID { get; set; }
        public System.Guid PMProcedureID { get; set; }
        public System.Guid ControlTypeID { get; set; }
        public System.Guid DataTypeID { get; set; }
        public System.Guid GraphTypeID { get; set; }
        public string LabelCaption { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public Nullable<double> WarningLow { get; set; }
        public Nullable<double> WarningHigh { get; set; }
        public bool IsMandatory { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> NoOfHistoricValues { get; set; }
        public string UnitCaption { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ControlType ControlType { get; set; }
        public virtual DataType DataType { get; set; }
        public virtual GraphType GraphType { get; set; }
        public virtual PMProcedure PMProcedure { get; set; }
    }
}
