//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMServiceForms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PMServiceForms()
        {
            this.PMDiagramValue = new HashSet<PMDiagramValue>();
            this.PMProcedureValue = new HashSet<PMProcedureValue>();
            this.UserMeasurementAlerts = new HashSet<UserMeasurementAlerts>();
        }
    
        public System.Guid PMServiceFormID { get; set; }
        public Nullable<System.Guid> RigEquipmentID { get; set; }
        public System.Guid PMServiceFormDefinitionID { get; set; }
        public Nullable<System.DateTime> PMServiceDate { get; set; }
        public string PMServiceHours { get; set; }
        public string Comments { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<System.DateTime> AcknowledgedOn { get; set; }
        public string AcknowledgedBy { get; set; }
        public Nullable<System.Guid> OrgUnitID { get; set; }
        public Nullable<int> SecStatus { get; set; }
        public Nullable<int> RejectionCount { get; set; }
        public Nullable<System.Guid> PMSubmittedByRoleID { get; set; }
        public string RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedOn { get; set; }
        public string ResubmittedBy { get; set; }
        public Nullable<System.DateTime> ResubmittedOn { get; set; }
        public string AcceptedBy { get; set; }
        public Nullable<System.DateTime> AcceptedOn { get; set; }
        public string RejectionComments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMDiagramValue> PMDiagramValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMProcedureValue> PMProcedureValue { get; set; }
        public virtual PMServiceFormDefinition PMServiceFormDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMeasurementAlerts> UserMeasurementAlerts { get; set; }
        public virtual RigEquipment RigEquipment { get; set; }
    }
}
