//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMServiceFormSectionDiagrams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PMServiceFormSectionDiagrams()
        {
            this.PMDiagramValue = new HashSet<PMDiagramValue>();
        }
    
        public System.Guid PMServiceFormSectionDiagramsID { get; set; }
        public System.Guid PMServiceFormSectionID { get; set; }
        public System.Guid PMDiagramID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual PMDiagram PMDiagram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMDiagramValue> PMDiagramValue { get; set; }
        public virtual PMServiceFormSection PMServiceFormSection { get; set; }
    }
}
