//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMServiceFormDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PMServiceFormDefinition()
        {
            this.PMServiceFormSection = new HashSet<PMServiceFormSection>();
            this.PMServiceForms = new HashSet<PMServiceForms>();
        }
    
        public System.Guid PMServiceFormDefinitionID { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
        public Nullable<System.Guid> EquipmentID { get; set; }
        public Nullable<System.Guid> EquipmentScheduleId { get; set; }
        public Nullable<System.Guid> FormTypeID { get; set; }
        public string FormName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string RussianFormName { get; set; }
        public string RevisionNo { get; set; }
        public Nullable<bool> IsObsolete { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual EquipmentSchedule EquipmentSchedule { get; set; }
        public virtual FormTypes FormTypes { get; set; }
        public virtual OrgRole OrgRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMServiceFormSection> PMServiceFormSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMServiceForms> PMServiceForms { get; set; }
    }
}
