//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RamsAlert
    {
        public System.Guid RamsAlertID { get; set; }
        public Nullable<System.Guid> OrgUnitID { get; set; }
        public string AlertMessage { get; set; }
        public string AlertType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.Guid> EquipmentDocumentID { get; set; }
        public Nullable<bool> IsDownloaded { get; set; }
    
        public virtual OrgUnit OrgUnit { get; set; }
    }
}
