//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleifValveRegisterDetails
    {
        public System.Guid ReleifValveRegisterDetailsID { get; set; }
        public System.Guid ReleifValveRegisterID { get; set; }
        public System.Guid RigEquipmentID { get; set; }
        public string EntryID { get; set; }
        public string PartNumber { get; set; }
        public string CertNo { get; set; }
        public Nullable<System.DateTime> DateMFG { get; set; }
        public string SetPressure { get; set; }
        public Nullable<System.DateTime> LastInspection { get; set; }
        public Nullable<System.DateTime> NextInspection { get; set; }
        public string CompletedBy { get; set; }
        public string WitnessedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ReleifValveRegister ReleifValveRegister { get; set; }
        public virtual RigEquipment RigEquipment { get; set; }
    }
}
