//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTabSecUSerGroup
    {
        public System.Guid ReportTabSecUSerGroupID { get; set; }
        public System.Guid ReportTabID { get; set; }
        public System.Guid UserGroupID { get; set; }
        public string Createdby { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOnDate { get; set; }
    
        public virtual SecUserGroup SecUserGroup { get; set; }
    }
}
