//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigDetails_1
    {
        public System.Guid OrgUnitID { get; set; }
        public string RigName { get; set; }
        public string RigType { get; set; }
        public string RigOwner { get; set; }
        public string Description { get; set; }
        public string YearBuilt { get; set; }
        public string ConstructedBy { get; set; }
        public string CurrentLocation { get; set; }
        public string CurrentStatus { get; set; }
        public string NoOfLoadsRig { get; set; }
        public string NoOfLoadsCamp { get; set; }
        public string FuelConsumption { get; set; }
        public string RigPhone { get; set; }
        public Nullable<bool> IsCountryRig { get; set; }
        public string VerticalDepthRating { get; set; }
        public string MaxStaticHookLoad { get; set; }
        public string MaxSetBackLoad { get; set; }
        public string MaxRotaryLoad { get; set; }
        public string MaxTopDriveLoad { get; set; }
        public string Fuel { get; set; }
        public string DrillWater { get; set; }
        public string PotableWater { get; set; }
        public string ActiveDrillingFluid { get; set; }
        public string ReserveDrillingFluid { get; set; }
        public string WaterForFireFighting { get; set; }
        public string BulkMud { get; set; }
        public string BulkCement { get; set; }
        public Nullable<decimal> NPTRates { get; set; }
        public Nullable<decimal> ContractNPTAllowance { get; set; }
        public Nullable<decimal> ContractNPTRates { get; set; }
        public byte[] RigImage { get; set; }
        public Nullable<bool> RigStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> ContractExpiryDate { get; set; }
        public string RigTypeSec { get; set; }
        public Nullable<int> MastHeight { get; set; }
        public string MastRackingCapacity { get; set; }
        public string SubstructureStyle { get; set; }
        public Nullable<decimal> SubstructureHeight { get; set; }
        public Nullable<decimal> SubstructureClearHeight { get; set; }
        public string IACDCodeCountry { get; set; }
    }
}
