//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigEquipment_temp
    {
        public System.Guid RigEquipmentID { get; set; }
        public System.Guid OrgUnitID { get; set; }
        public Nullable<System.Guid> EquipmentID { get; set; }
        public Nullable<System.Guid> ParentRigEquipmentID { get; set; }
        public string SerialNo { get; set; }
        public string MaterialNumber { get; set; }
        public string RigEquipmentName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> FunctionStartDate { get; set; }
        public Nullable<System.Guid> EquipmentCriticalityId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> UniqueId { get; set; }
        public Nullable<System.Guid> Destination { get; set; }
        public string PONumber { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<bool> IsRental { get; set; }
        public Nullable<System.Guid> CurrentEquipmentId { get; set; }
    }
}
