//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigEquipmentSchedule_1
    {
        public System.Guid RigEquipScheduleID { get; set; }
        public Nullable<System.Guid> EquipmentScheduleId { get; set; }
        public Nullable<System.Guid> RigEquipmentID { get; set; }
        public Nullable<int> RecurranceCalendarValue { get; set; }
        public Nullable<int> CalendarAlertMargin { get; set; }
        public Nullable<int> RecurranceMeterHour { get; set; }
        public Nullable<int> CalendarEscalationMargin { get; set; }
        public Nullable<int> MeterAlertMargin { get; set; }
        public Nullable<int> MeterEscalationMargin { get; set; }
        public Nullable<bool> IsScheduleSuspended { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string IACDCodeCountry { get; set; }
    }
}
