//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigEquipmentOverallHours
    {
        public System.Guid RigEquipmentID { get; set; }
        public string OverallType { get; set; }
        public double HoursRecorded { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public System.Guid OverHaulID { get; set; }
    
        public virtual RigEquipment RigEquipment { get; set; }
    }
}
