//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigEquipmentUnscheduledRepairDetails
    {
        public System.Guid RigEquipmentUnscheduledRepairDetailID { get; set; }
        public System.Guid RigEquipmentUnscheduledRepairsID { get; set; }
        public string Description { get; set; }
        public string Quantity { get; set; }
        public string PartNumber { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual RigEquipmentUnscheduledRepairs RigEquipmentUnscheduledRepairs { get; set; }
    }
}
