//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigEquipmentOneTimeJobTasks
    {
        public System.Guid RigEquipmentOneTimeJobTasksID { get; set; }
        public Nullable<System.Guid> RigEquipmentOneTimeJobID { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string TaskName { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual RigEquipmentOneTimeJob RigEquipmentOneTimeJob { get; set; }
    }
}
