//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigEquipmentScheduleJobs
    {
        public System.Guid RigEquipmentScheduleJobsID { get; set; }
        public System.Guid RoleID { get; set; }
        public System.Guid RigEquipScheduleID { get; set; }
        public string LoginID { get; set; }
        public System.DateTime JobDate { get; set; }
        public Nullable<double> JobMeterHours { get; set; }
        public Nullable<System.DateTime> JobCompletedOn { get; set; }
        public bool IsSuspended { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.Guid> TaskID { get; set; }
        public string TaskType { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.Guid> EquipmentCriticalityId { get; set; }
        public Nullable<System.DateTime> JobAlertDate { get; set; }
        public Nullable<System.DateTime> JobOverDueDate { get; set; }
        public Nullable<double> JobCompletedOnMeterHours { get; set; }
    
        public virtual OrgRole OrgRole { get; set; }
        public virtual RigEquipmentSchedule RigEquipmentSchedule { get; set; }
        public virtual SecUser SecUser { get; set; }
    }
}
