//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigEquipmentInspections
    {
        public System.Guid RigEquipmentInspectionsID { get; set; }
        public Nullable<System.Guid> RigEquipmentID { get; set; }
        public Nullable<System.Guid> RigEquipScheduleID { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public byte[] InspectionCertificate { get; set; }
        public string InspectionCertificateNumber { get; set; }
        public string InspectionCompany { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> IACDCode { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual RigEquipment RigEquipment { get; set; }
    }
}
