//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigEquipmentSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RigEquipmentSchedule()
        {
            this.RigEquipmentScheduleJobs = new HashSet<RigEquipmentScheduleJobs>();
        }
    
        public System.Guid RigEquipScheduleID { get; set; }
        public Nullable<System.Guid> EquipmentScheduleId { get; set; }
        public Nullable<System.Guid> RigEquipmentID { get; set; }
        public Nullable<int> RecurranceCalendarValue { get; set; }
        public Nullable<int> CalendarAlertMargin { get; set; }
        public Nullable<int> RecurranceMeterHour { get; set; }
        public Nullable<int> CalendarEscalationMargin { get; set; }
        public Nullable<int> MeterAlertMargin { get; set; }
        public Nullable<int> MeterEscalationMargin { get; set; }
        public Nullable<bool> IsScheduleSuspended { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual EquipmentSchedule EquipmentSchedule { get; set; }
        public virtual EquipmentSchedule EquipmentSchedule1 { get; set; }
        public virtual EquipmentSchedule EquipmentSchedule2 { get; set; }
        public virtual RigEquipment RigEquipment { get; set; }
        public virtual RigEquipment RigEquipment1 { get; set; }
        public virtual RigEquipment RigEquipment2 { get; set; }
        public virtual RigEquipment RigEquipment3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigEquipmentScheduleJobs> RigEquipmentScheduleJobs { get; set; }
    }
}
