//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigEquipmentTransferDetails
    {
        public System.Guid RigEquipmentTransferDetailsID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> RigEquipmentID { get; set; }
        public Nullable<System.Guid> EquipmentTransferHistoryLogID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual EquipmentTransferHistoryLog EquipmentTransferHistoryLog { get; set; }
        public virtual RigEquipment RigEquipment { get; set; }
    }
}
