//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigEq_18MonthsPlanDetails
    {
        public System.Guid RigEq_PlanDetailsID { get; set; }
        public Nullable<System.Guid> RigEquipmentPlanID { get; set; }
        public Nullable<System.Guid> RigEquipmentScheduleJobsID { get; set; }
        public Nullable<System.DateTime> JobPlanDate { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}
