//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigEquipmentOneTimeJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RigEquipmentOneTimeJob()
        {
            this.RigEquipmentOneTimeJobTasks = new HashSet<RigEquipmentOneTimeJobTasks>();
        }
    
        public System.Guid RigEquipmentOneTimeJobID { get; set; }
        public Nullable<System.Guid> RigEquipmentID { get; set; }
        public Nullable<System.Guid> OrgUnitID { get; set; }
        public Nullable<bool> JobCompleted { get; set; }
        public string Comments { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public Nullable<System.Guid> EquipmentID { get; set; }
        public Nullable<System.Guid> EquipmentFamilyID { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.Guid> DocumentID { get; set; }
        public string ItemType { get; set; }
        public Nullable<int> UniqueId { get; set; }
        public Nullable<System.Guid> JobComplete_JustificationDoc { get; set; }
    
        public virtual OrgUnit OrgUnit { get; set; }
        public virtual RigEquipment RigEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigEquipmentOneTimeJobTasks> RigEquipmentOneTimeJobTasks { get; set; }
    }
}
