//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMRSuperordinateRoutingHierarchy
    {
        public int RMRSuperordinateRoutingHierarchyID { get; set; }
        public System.Guid SubordinateRoleID { get; set; }
        public System.Guid SuperordinateRoleID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string ProcessCycle { get; set; }
        public bool IsDeleted { get; set; }
    }
}
