//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptsRepository
    {
        public System.Guid ScriptID { get; set; }
        public Nullable<System.Guid> OrgUnitID { get; set; }
        public string Script { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string ExecuteAfterTable { get; set; }
        public string ExecuteBeforeAction { get; set; }
        public string ClientApplicationVersion { get; set; }
    }
}
