//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecPolicy
    {
        public System.Guid PolicyID { get; set; }
        public System.Guid PolicyGroupID { get; set; }
        public string PolicyNamePrm { get; set; }
        public string PolicyNameSec { get; set; }
        public decimal PolicyType { get; set; }
        public Nullable<decimal> ApplicationIdleTime { get; set; }
        public string TimeExpression { get; set; }
        public string PasswordExpression { get; set; }
        public Nullable<decimal> PasswordHistoryCount { get; set; }
        public decimal PasswordExpiryCount { get; set; }
        public Nullable<decimal> PasswordExpiryWarningCount { get; set; }
        public Nullable<bool> IsAutoReset { get; set; }
        public bool IsMultiLogin { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string ReportDBServer { get; set; }
        public string ReportDBCataLog { get; set; }
        public string ReportDBUser { get; set; }
        public string ReportDBPassword { get; set; }
    
        public virtual SecPolicyGroup SecPolicyGroup { get; set; }
    }
}
