//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecPasswordHistory
    {
        public System.Guid PasswordHistoryID { get; set; }
        public string LoginID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Password { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual SecUser SecUser { get; set; }
    }
}
