//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecUserGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecUserGroup()
        {
            this.ReportTabSecUSerGroup = new HashSet<ReportTabSecUSerGroup>();
            this.SecUserGroupPermission = new HashSet<SecUserGroupPermission>();
            this.SecUserUserGroup = new HashSet<SecUserUserGroup>();
            this.SecUserGroupRelation = new HashSet<SecUserGroupRelation>();
            this.SecUserGroupRelation1 = new HashSet<SecUserGroupRelation>();
        }
    
        public System.Guid UserGroupID { get; set; }
        public string GroupNamePrm { get; set; }
        public string GroupNameSec { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportTabSecUSerGroup> ReportTabSecUSerGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecUserGroupPermission> SecUserGroupPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecUserUserGroup> SecUserUserGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecUserGroupRelation> SecUserGroupRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecUserGroupRelation> SecUserGroupRelation1 { get; set; }
    }
}
