//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECUSER_bk
    {
        public string LoginID { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string FullNameSec { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public string EmailURL { get; set; }
        public Nullable<System.DateTime> WhenDeleted { get; set; }
        public string PreferedCulture { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public byte IsSystem { get; set; }
        public string StatusID { get; set; }
        public System.Guid PolicyGroupID { get; set; }
        public string PeopleSoftID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.Guid> CountryOrgUnitID { get; set; }
        public Nullable<bool> EmailAlertsRequired { get; set; }
        public string UserComputerID { get; set; }
        public string VersionNo { get; set; }
        public string WhatsNewVersionNo { get; set; }
    }
}
