//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecUser()
        {
            this.DailyLog = new HashSet<DailyLog>();
            this.ImprovementCommitment = new HashSet<ImprovementCommitment>();
            this.ImprovementCommitment1 = new HashSet<ImprovementCommitment>();
            this.ImprovementCommitment2 = new HashSet<ImprovementCommitment>();
            this.ImprovementCommitment3 = new HashSet<ImprovementCommitment>();
            this.RigEquipmentScheduleJobs = new HashSet<RigEquipmentScheduleJobs>();
            this.RigRepairAlerts = new HashSet<RigRepairAlerts>();
            this.SecActivityLog = new HashSet<SecActivityLog>();
            this.SecPasswordHistory = new HashSet<SecPasswordHistory>();
            this.UserMeasurementAlerts = new HashSet<UserMeasurementAlerts>();
            this.SecUserUserGroup = new HashSet<SecUserUserGroup>();
        }
    
        public string LoginID { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string FullNameSec { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public string EmailURL { get; set; }
        public Nullable<System.DateTime> WhenDeleted { get; set; }
        public string PreferedCulture { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public byte IsSystem { get; set; }
        public string StatusID { get; set; }
        public System.Guid PolicyGroupID { get; set; }
        public string PeopleSoftID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte[] UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.Guid> CountryOrgUnitID { get; set; }
        public Nullable<bool> EmailAlertsRequired { get; set; }
        public string UserComputerID { get; set; }
        public string VersionNo { get; set; }
        public string WhatsNewVersionNo { get; set; }
        public Nullable<bool> LoginStatus { get; set; }
        public Nullable<System.DateTime> LastLoginStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyLog> DailyLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImprovementCommitment> ImprovementCommitment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImprovementCommitment> ImprovementCommitment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImprovementCommitment> ImprovementCommitment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImprovementCommitment> ImprovementCommitment3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigEquipmentScheduleJobs> RigEquipmentScheduleJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigRepairAlerts> RigRepairAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecActivityLog> SecActivityLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecPasswordHistory> SecPasswordHistory { get; set; }
        public virtual SecPolicyGroup SecPolicyGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMeasurementAlerts> UserMeasurementAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecUserUserGroup> SecUserUserGroup { get; set; }
        public virtual SecUserStatus SecUserStatus { get; set; }
    }
}
