//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public System.Guid OrgUnitID { get; set; }
        public Nullable<System.Guid> EquipmentID { get; set; }
        public string RigEquipmentName { get; set; }
        public string Description { get; set; }
        public bool IsSpare { get; set; }
        public Nullable<System.Guid> RigEquipmentID { get; set; }
    }
}
