//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEmailNotification
    {
        public long UserEmailNotificationID { get; set; }
        public System.Guid AlertID { get; set; }
        public string EmailRecipient { get; set; }
        public string EmailBody { get; set; }
        public string EmailSubject { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public string ErrorOnSending { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}
