//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGeneratorDetailSpecifications
    {
        public string Country { get; set; }
        public string Rig { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> AssetID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string SerialNo { get; set; }
        public string Frame { get; set; }
        public string Volts { get; set; }
        public string Power_Factor { get; set; }
        public string Frequency__Hz_ { get; set; }
        public string KVA { get; set; }
        public string Kilowatt { get; set; }
    }
}
