//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPMFormsWithEquipmentNameConflicts_Summary
    {
        public string OrgNamePrm { get; set; }
        public string PMEquipmentName { get; set; }
        public string PMDEquipmentName { get; set; }
        public string FormName { get; set; }
        public System.Guid OrgUnitID { get; set; }
        public System.Guid PMEquipmentID { get; set; }
        public System.Guid PMDEquipmentID { get; set; }
        public System.Guid PMServiceFormDefinitionID { get; set; }
        public Nullable<int> Conflict_Count { get; set; }
    }
}
