//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPMFormsWithEquipmentNameConflicts_Details
    {
        public string Equipment_Name_By_PM { get; set; }
        public string Equipment_Name_By_PMD { get; set; }
        public string FormName { get; set; }
        public string RigEquipmentName { get; set; }
        public string OrgNameprm { get; set; }
    }
}
