//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebRouting
    {
        public System.Guid WebRoutingID { get; set; }
        public string PermissionID { get; set; }
        public string Name { get; set; }
        public string NgRoute { get; set; }
        public Nullable<int> SequenceOrder { get; set; }
        public string ControllerName { get; set; }
        public string TemplateUrl { get; set; }
        public Nullable<bool> IsChildTab { get; set; }
    }
}
