//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebView
    {
        public int WebViewID { get; set; }
        public string ViewName { get; set; }
        public string ParentView { get; set; }
        public string NgRoute { get; set; }
    }
}
